export interface VideoEntry {
  title: string
  artist: string
  videoId: string
  year: number
  tags: string[]
}

export type Decade = '60s' | '70s' | '80s' | '90s' | '00s' | '10s' | '20s'

export const videos: Record<Decade, VideoEntry[]> = {
  "60s": [
    {"title":"Can't Help Falling in Love","artist":"Elvis Presley","videoId":"vGJTaP6anOU","year":1961,"tags":["pop"]},
    {"title":"I Want to Hold Your Hand","artist":"The Beatles","videoId":"jenWdylTtzs","year":1963,"tags":["rock"]},
    {"title":"Respect","artist":"Aretha Franklin","videoId":"6FOUqQt3Kg0","year":1967,"tags":["soul"]},
    {"title":"Stand By Me","artist":"Ben E. King","videoId":"hwZNL7QVJjE","year":1961,"tags":["soul"]},
    {"title":"My Girl","artist":"The Temptations","videoId":"qEztui18cA8","year":1964,"tags":["motown"]},
    {"title":"California Dreamin'","artist":"The Mamas & the Papas","videoId":"N-aK6JnyFmk","year":1965,"tags":["folk"]},
    {"title":"Paint It Black","artist":"The Rolling Stones","videoId":"O4irXQhgMqg","year":1966,"tags":["rock"]},
    {"title":"Light My Fire","artist":"The Doors","videoId":"qoX6AKuYWL8","year":1967,"tags":["rock"]},
    {"title":"Good Vibrations","artist":"The Beach Boys","videoId":"Eab_beh07HU","year":1966,"tags":["pop"]},
    {"title":"Come Together","artist":"The Beatles","videoId":"45cYwDMibGo","year":1969,"tags":["rock"]},
    {"title":"These Boots Are Made for Walkin'","artist":"Nancy Sinatra","videoId":"SbyAZQ45uww","year":1966,"tags":["pop"]},
    {"title":"A Whiter Shade of Pale","artist":"Procol Harum","videoId":"Mb3iPP-tHdA","year":1967,"tags":["rock"]},
    {"title":"The Sound of Silence","artist":"Simon & Garfunkel","videoId":"4zLfCnGVeL4","year":1965,"tags":["folk"]},
    {"title":"Sugar Sugar","artist":"The Archies","videoId":"h9nE2spOw_o","year":1969,"tags":["pop"]},
    {"title":"Surfin' USA","artist":"The Beach Boys","videoId":"EDb303T-B1w","year":1963,"tags":["pop"]},
    {"title":"Twist and Shout","artist":"The Beatles","videoId":"2RicaUqd9Hg","year":1963,"tags":["rock"]},
    {"title":"Be My Baby","artist":"The Ronettes","videoId":"jSPpbOGnFgk","year":1963,"tags":["pop"]},
    {"title":"Runaway","artist":"Del Shannon","videoId":"0S13mP_pfEc","year":1961,"tags":["rock"]},
    {"title":"I Heard It Through the Grapevine","artist":"Marvin Gaye","videoId":"cXWHpbpNdHE","year":1968,"tags":["soul"]},
    {"title":"Piece of My Heart","artist":"Janis Joplin","videoId":"SCngPse1iiI","year":1968,"tags":["rock"]},
    {"title":"Hound Dog","artist":"Elvis Presley","videoId":"kJQP7kiw5Fk","year":1956,"tags":["rock"]},
    {"title":"Johnny B. Goode","artist":"Chuck Berry","videoId":"ZFo8-JqzP20","year":1958,"tags":["rock"]},
    {"title":"Louie Louie","artist":"The Kingsmen","videoId":"AORlrpVH2c8","year":1963,"tags":["rock"]},
    {"title":"Whole Lotta Love","artist":"Led Zeppelin","videoId":"HQmmjptKCwY","year":1969,"tags":["rock"]},
    {"title":"Satisfaction","artist":"The Rolling Stones","videoId":"yDfFIPfAKwE","year":1965,"tags":["rock"]},
    {"title":"Mony Mony","artist":"Tommy James","videoId":"gFjt76YXpkA","year":1968,"tags":["pop"]},
    {"title":"She Loves You","artist":"The Beatles","videoId":"mQmf0T3YyYM","year":1963,"tags":["rock"]},
    {"title":"Itsy Bitsy Teenie Weenie Yellow Polka Dot Bikini","artist":"Brian Hyland","videoId":"h_aAn32Yk2c","year":1960,"tags":["pop"]},
    {"title":"Build Me Up Buttercup","artist":"The Foundations","videoId":"oel8Z6irdkk","year":1968,"tags":["soul"]},
    {"title":"Mrs. Brown, You've Got a Lovely Daughter","artist":"Herman's Hermits","videoId":"gZD9q3m3CPI","year":1965,"tags":["pop"]},
    {"title":"Help!","artist":"The Beatles","videoId":"4u_jHc-d0Ow","year":1965,"tags":["rock"]},
    {"title":"Hang On Sloopy","artist":"The McCoys","videoId":"QzEbS9WTJbU","year":1965,"tags":["rock"]},
    {"title":"Downtown","artist":"Petula Clark","videoId":"wNLmKwE8HAg","year":1964,"tags":["pop"]},
    {"title":"A Boy Like You","artist":"Freddie & The Dreamers","videoId":"j6YKqBZJbEI","year":1963,"tags":["pop"]},
    {"title":"Woolly Bully","artist":"Sam the Sham","videoId":"h0u3MlCSB84","year":1965,"tags":["rock"]},
    {"title":"Wild Thing","artist":"The Troggs","videoId":"tKIrFnuAjpY","year":1966,"tags":["rock"]},
    {"title":"Sunshine Superman","artist":"Donovan","videoId":"rQ0vUmPLMFI","year":1966,"tags":["folk"]},
    {"title":"Time Is on My Side","artist":"The Rolling Stones","videoId":"L8z4_CHrmXA","year":1964,"tags":["rock"]},
    {"title":"Norwegian Wood","artist":"The Beatles","videoId":"N0vy6l0OPRU","year":1965,"tags":["rock"]},
    {"title":"I Feel Fine","artist":"The Beatles","videoId":"2n6J5AvOp2M","year":1964,"tags":["rock"]},
    {"title":"I Got You Babe","artist":"Sonny & Cher","videoId":"SyAMZlMsjew","year":1965,"tags":["pop"]},
    {"title":"Where Did Our Love Go","artist":"The Supremes","videoId":"f7aVxMvM1ys","year":1964,"tags":["soul"]},
    {"title":"Stop! In the Name of Love","artist":"The Supremes","videoId":"jU-XKrfXrZI","year":1965,"tags":["soul"]},
    {"title":"You Can't Hurry Love","artist":"The Supremes","videoId":"u1f2PEeRPD4","year":1966,"tags":["soul"]},
    {"title":"Reach Out I'll Be There","artist":"Four Tops","videoId":"zDfMO-iywhQ","year":1966,"tags":["soul"]},
    {"title":"I Heard It Through the Grapevine (Gladys Knight)","artist":"Gladys Knight","videoId":"xNdKXh-KH-k","year":1967,"tags":["soul"]},
    {"title":"Proud Mary","artist":"Creedence Clearwater Revival","videoId":"gkj7w1qFMvw","year":1968,"tags":["rock"]},
    {"title":"Have You Ever Seen the Rain","artist":"Creedence Clearwater Revival","videoId":"Co3Yqh8KwHA","year":1970,"tags":["rock"]},
    {"title":"Green River","artist":"Creedence Clearwater Revival","videoId":"0OZ5p-jrwRg","year":1969,"tags":["rock"]},
    {"title":"Bad Moon Rising","artist":"Creedence Clearwater Revival","videoId":"GCHOlVOtVqE","year":1969,"tags":["rock"]},
    {"title":"House of the Rising Sun","artist":"The Animals","videoId":"0s4aIQrz4T0","year":1964,"tags":["rock"]},
    {"title":"To Build a Home","artist":"The Cinematic Orchestra","videoId":"oUFJJNQGwhk","year":1968,"tags":["rock"]},
    {"title":"Black Magic Woman","artist":"Santana","videoId":"EqVxJrz0Vv0","year":1968,"tags":["rock"]},
    {"title":"All Right Now","artist":"Free","videoId":"kJ0h9hMBLo0","year":1970,"tags":["rock"]},
    {"title":"Smoke on the Water","artist":"Deep Purple","videoId":"zUwEIt9z7-8","year":1971,"tags":["rock"]},
    {"title":"Do You Wanna Dance","artist":"Bobby Freeman","videoId":"x5qM5jRWWgM","year":1958,"tags":["rock"]},
    {"title":"Let's Twist Again","artist":"Chubby Checker","videoId":"wYYN0MmXfYY","year":1961,"tags":["pop"]},
    {"title":"Shout","artist":"The Isley Brothers","videoId":"4x9OKb7FFJA","year":1959,"tags":["soul"]},
    {"title":"Land of 1000 Dances","artist":"Wilson Pickett","videoId":"Ixu4hAIQfJw","year":1966,"tags":["soul"]},
    {"title":"Uptight (Everything's Alright)","artist":"Stevie Wonder","videoId":"fqC7qxN7R-s","year":1966,"tags":["soul"]},
    {"title":"For Once in My Life","artist":"Stevie Wonder","videoId":"4-N4eE6R4Gk","year":1968,"tags":["soul"]},
    {"title":"My World Is Empty Without You","artist":"The Supremes","videoId":"ugCqA_7qdPo","year":1965,"tags":["soul"]},
    {"title":"Dancing in the Street","artist":"Martha and the Vandellas","videoId":"Hf4oaZBpvWA","year":1964,"tags":["soul"]},
    {"title":"Money (That's What I Want)","artist":"Barrett Strong","videoId":"FTQuFSDVCwc","year":1959,"tags":["soul"]},
    {"title":"Do Not Disturb","artist":"The Supremes","videoId":"wBEzP8c6Yc8","year":1965,"tags":["soul"]},
    {"title":"Venus","artist":"Shocking Blue","videoId":"1Mwjf23JqgI","year":1969,"tags":["pop"]},
    {"title":"Unchained Melody","artist":"The Righteous Brothers","videoId":"LR1kFMVgFKE","year":1965,"tags":["soul"]},
    {"title":"Georgia on My Mind","artist":"Ray Charles","videoId":"UwQ6nJ0kDWo","year":1960,"tags":["soul"]},
    {"title":"Unforgettable","artist":"Nat King Cole","videoId":"VZUEqWZzQJQ","year":1951,"tags":["soul"]},
    {"title":"Dream a Little Dream of Me","artist":"Ella Fitzgerald","videoId":"RCwRhZnhE_8","year":1931,"tags":["jazz"]},
    {"title":"I Will Always Love You (Original)","artist":"Dolly Parton","videoId":"MEjPg_AyYvA","year":1974,"tags":["country"]},
    {"title":"Moon River","artist":"Henry Mancini","videoId":"ywfXZJUVf5g","year":1961,"tags":["easy"]},
    {"title":"Catch a Wave","artist":"The Beach Boys","videoId":"QkQKKW4NyAA","year":1963,"tags":["pop"]},
    {"title":"Barbara Ann","artist":"The Beach Boys","videoId":"R1m4eXpD9CE","year":1965,"tags":["pop"]},
    {"title":"Wouldn't It Be Nice","artist":"The Beach Boys","videoId":"e5qF70aFZb8","year":1966,"tags":["pop"]},
    {"title":"God Only Knows","artist":"The Beach Boys","videoId":"d-EFiYNp-W8","year":1966,"tags":["pop"]},
    {"title":"Help Me Rhonda","artist":"The Beach Boys","videoId":"S1ixo6Xvdfg","year":1965,"tags":["pop"]},
    {"title":"Pet Sounds","artist":"The Beach Boys","videoId":"1n30D5L8Dbs","year":1966,"tags":["pop"]},
    {"title":"Wildwood Flower","artist":"Tammy Wynette","videoId":"K-dBl1ePx1c","year":1965,"tags":["country"]},
    {"title":"I Walk the Line","artist":"Johnny Cash","videoId":"xvqeSJlgaNg","year":1956,"tags":["country"]},
    {"title":"Folsom Prison Blues","artist":"Johnny Cash","videoId":"pT8Yx4-Ov1w","year":1955,"tags":["country"]},
    {"title":"Ring of Fire","artist":"Johnny Cash","videoId":"MxF5g3xQk6g","year":1963,"tags":["country"]},
    {"title":"Crazy","artist":"Patsy Cline","videoId":"BqDKvW3Zq1Q","year":1961,"tags":["country"]},
    {"title":"Jolene","artist":"Dolly Parton","videoId":"4JkIs37a2JE","year":1973,"tags":["country"]},
    {"title":"Stand By Your Man","artist":"Tammy Wynette","videoId":"K-dBl1ePx1c","year":1968,"tags":["country"]},
    {"title":"Mambo No. 5","artist":"Pérez Prado","videoId":"wPtvQ-DxYc0","year":1949,"tags":["latin"]},
    {"title":"El Condor Pasa","artist":"Simon & Garfunkel","videoId":"ZrZn8Ln4ryg","year":1970,"tags":["folk"]},
    {"title":"Guantanamera","artist":"Pete Seeger","videoId":"fyRXWIVr_nE","year":1960,"tags":["folk"]},
    {"title":"Blowin' in the Wind","artist":"Bob Dylan","videoId":"GMEq3yxSxxc","year":1962,"tags":["folk"]},
    {"title":"The Times They Are a-Changin'","artist":"Bob Dylan","videoId":"e_DqV1xdf-Y","year":1963,"tags":["folk"]},
    {"title":"Like a Rolling Stone","artist":"Bob Dylan","videoId":"e_DqV1xdf-Y","year":1965,"tags":["folk"]}
  ],
  "70s": [
    {"title":"Bohemian Rhapsody","artist":"Queen","videoId":"fJ9rUzIMcZQ","year":1975,"tags":["rock"]},
    {"title":"Stayin' Alive","artist":"Bee Gees","videoId":"I_izvAbhExY","year":1977,"tags":["disco"]},
    {"title":"Hotel California","artist":"Eagles","videoId":"EqPtz5qN7HM","year":1976,"tags":["rock"]},
    {"title":"Imagine","artist":"John Lennon","videoId":"YkgkThdzX-8","year":1971,"tags":["pop"]},
    {"title":"Superstition","artist":"Stevie Wonder","videoId":"0CFuCYNx-1g","year":1972,"tags":["funk"]},
    {"title":"Dancing Queen","artist":"ABBA","videoId":"xFrGuyw1V8s","year":1976,"tags":["pop"]},
    {"title":"Le Freak","artist":"Chic","videoId":"h1qQ1SKNlgY","year":1978,"tags":["disco"]},
    {"title":"September","artist":"Earth, Wind & Fire","videoId":"Gs069dndIYk","year":1978,"tags":["funk"]},
    {"title":"Go Your Own Way","artist":"Fleetwood Mac","videoId":"6ul-cZyuYq4","year":1977,"tags":["rock"]},
    {"title":"Roxanne","artist":"The Police","videoId":"3T1c7GkzRQQ","year":1978,"tags":["rock"]},
    {"title":"We Will Rock You","artist":"Queen","videoId":"-tJYN-eG1zk","year":1977,"tags":["rock"]},
    {"title":"Blame It on the Boogie","artist":"Jacksons","videoId":"nqxVMLVe62U","year":1978,"tags":["funk"]},
    {"title":"I Will Survive","artist":"Gloria Gaynor","videoId":"6dYWe1c3OyU","year":1978,"tags":["disco"]},
    {"title":"Dreams","artist":"Fleetwood Mac","videoId":"5oWyMakvQew","year":1977,"tags":["rock"]},
    {"title":"Let It Be","artist":"The Beatles","videoId":"QDYfEBY9NM4","year":1970,"tags":["rock"]},
    {"title":"American Pie","artist":"Don McLean","videoId":"PRpiBpDy7MQ","year":1971,"tags":["folk"]},
    {"title":"Car Wash","artist":"Rose Royce","videoId":"PkxaunLybuM","year":1976,"tags":["funk"]},
    {"title":"Play That Funky Music","artist":"Wild Cherry","videoId":"MDZsNksbw2Q","year":1976,"tags":["funk"]},
    {"title":"Don't Stop Me Now","artist":"Queen","videoId":"HgzGwKwLmgM","year":1979,"tags":["rock"]},
    {"title":"Heart of Glass","artist":"Blondie","videoId":"WGU_4-5RaxU","year":1979,"tags":["pop"]},
    {"title":"Night Fever","artist":"Bee Gees","videoId":"oWrRKPqFu-w","year":1977,"tags":["disco"]},
    {"title":"Disco Inferno","artist":"Trammps","videoId":"s7pZSbSHVGo","year":1976,"tags":["disco"]},
    {"title":"I Will Survive","artist":"Gloria Gaynor","videoId":"6dYWe1c3OyU","year":1978,"tags":["disco"]},
    {"title":"Stayin' Alive","artist":"Bee Gees","videoId":"I_izvAbhExY","year":1977,"tags":["disco"]},
    {"title":"Boogie Wonderland","artist":"Earth, Wind & Fire","videoId":"o_1aF54DO2s","year":1978,"tags":["funk"]},
    {"title":"Get Down Tonight","artist":"KC & The Sunshine Band","videoId":"OfJ0DxkFHpQ","year":1975,"tags":["disco"]},
    {"title":"That's the Way (I Like It)","artist":"KC & The Sunshine Band","videoId":"B-L0XZH_2jI","year":1975,"tags":["disco"]},
    {"title":"Shake Your Groove Thing","artist":"Peaches & Herb","videoId":"P9q5GY0a0aU","year":1978,"tags":["disco"]},
    {"title":"Le Freak","artist":"Chic","videoId":"h1qQ1SKNlgY","year":1978,"tags":["disco"]},
    {"title":"Good Times","artist":"Chic","videoId":"7VJzPT_OAUI","year":1979,"tags":["disco"]},
    {"title":"Uptown Top Ranking","artist":"Althia & Donna","videoId":"2Q3KlQsCBg8","year":1977,"tags":["reggae"]},
    {"title":"No Woman No Cry","artist":"Bob Marley","videoId":"pPOz_8L2GKY","year":1974,"tags":["reggae"]},
    {"title":"Redemption Song","artist":"Bob Marley","videoId":"QnJFhuOWFAY","year":1980,"tags":["reggae"]},
    {"title":"Get Up Stand Up","artist":"Bob Marley","videoId":"H49e-r9-FfY","year":1973,"tags":["reggae"]},
    {"title":"Could You Be Loved","artist":"Bob Marley","videoId":"xnJG_IHqXhQ","year":1980,"tags":["reggae"]},
    {"title":"Three Little Birds","artist":"Bob Marley","videoId":"Wpc6eZrJSEE","year":1980,"tags":["reggae"]},
    {"title":"Waiting in Vain","artist":"Bob Marley","videoId":"JCXJ13s3S3g","year":1977,"tags":["reggae"]},
    {"title":"Exodus","artist":"Bob Marley","videoId":"mKmwdE5u59M","year":1977,"tags":["reggae"]},
    {"title":"Buffalo Soldier","artist":"Bob Marley","videoId":"P-F5A89-WPg","year":1983,"tags":["reggae"]},
    {"title":"One Love","artist":"Bob Marley","videoId":"WwzrtT__-OU","year":1977,"tags":["reggae"]},
    {"title":"Kung Fu Fighting","artist":"Carl Douglas","videoId":"IqkhzvsksKE","year":1974,"tags":["pop"]},
    {"title":"Spirit in the Sky","artist":"Norman Greenbaum","videoId":"AZKpByV5764","year":1969,"tags":["rock"]},
    {"title":"Ring My Bell","artist":"Anita Ward","videoId":"fAT0tHuKXBo","year":1979,"tags":["disco"]},
    {"title":"Dancing in Moonlight","artist":"King Harvest","videoId":"0i2cqIBO9KE","year":1972,"tags":["pop"]},
    {"title":"Afternoon Delight","artist":"Starland Vocal Band","videoId":"kJQP7kiw5Fk","year":1976,"tags":["pop"]},
    {"title":"Muskrat Love","artist":"Captain & Tennille","videoId":"szMHw3qxVFE","year":1976,"tags":["pop"]},
    {"title":"Love Will Keep Us Together","artist":"Captain & Tennille","videoId":"o3iNLU0Kl8w","year":1975,"tags":["pop"]},
    {"title":"Torn Between Two Lovers","artist":"Mary MacGregor","videoId":"39CnXTSEdZg","year":1976,"tags":["pop"]},
    {"title":"You Light Up My Life","artist":"Debby Boone","videoId":"VZLNvqSASn0","year":1977,"tags":["pop"]},
    {"title":"Mandy","artist":"Barry Manilow","videoId":"1VMscn0n5fw","year":1974,"tags":["pop"]},
    {"title":"Copacabana","artist":"Barry Manilow","videoId":"YeFbSI0yb5M","year":1978,"tags":["pop"]},
    {"title":"Feelings","artist":"Morris Albert","videoId":"n6K9dHHBdVg","year":1974,"tags":["pop"]},
    {"title":"How Deep Is Your Love","artist":"Bee Gees","videoId":"WsFpXjWfFSo","year":1977,"tags":["disco"]},
    {"title":"Disco Lady","artist":"Johnnie Taylor","videoId":"YPJ5EblG5-k","year":1975,"tags":["disco"]},
    {"title":"Dancing Queen","artist":"ABBA","videoId":"xFrGuyw1V8s","year":1976,"tags":["pop"]},
    {"title":"Mamma Mia","artist":"ABBA","videoId":"gbyy2xrSFFA","year":1975,"tags":["pop"]},
    {"title":"Waterloo","artist":"ABBA","videoId":"0iBmVfBIwQY","year":1974,"tags":["pop"]},
    {"title":"Fernando","artist":"ABBA","videoId":"k8EPbz7eXnw","year":1976,"tags":["pop"]},
    {"title":"Gimme Gimme Gimme","artist":"ABBA","videoId":"x44as3bTWrg","year":1979,"tags":["pop"]},
    {"title":"SOS","artist":"ABBA","videoId":"nS-W4F8DcIQ","year":1975,"tags":["pop"]},
    {"title":"Take a Chance on Me","artist":"ABBA","videoId":"qlH9u3zAv3A","year":1977,"tags":["pop"]},
    {"title":"The Winner Takes It All","artist":"ABBA","videoId":"sUXvj2GFVEU","year":1980,"tags":["pop"]},
    {"title":"Knock on Wood","artist":"Amii Stewart","videoId":"t_MKxW3nVbE","year":1978,"tags":["disco"]},
    {"title":"I'm Every Woman","artist":"Chaka Khan","videoId":"cxVHaFT9OMQ","year":1978,"tags":["funk"]},
    {"title":"Love's Theme","artist":"Love Unlimited Orchestra","videoId":"rI9tR6PJL3E","year":1973,"tags":["funk"]},
    {"title":"Rock with You","artist":"Michael Jackson","videoId":"tYzd0mDqkC0","year":1979,"tags":["disco"]},
    {"title":"Off the Wall","artist":"Michael Jackson","videoId":"8r-e65X3rN8","year":1979,"tags":["disco"]},
    {"title":"Don't Stop Till You Get Enough","artist":"Michael Jackson","videoId":"yURRmWISfLE","year":1979,"tags":["disco"]},
    {"title":"电视","artist":"香港電台","videoId":"ypF83J0Nqxg","year":1975,"tags":["cantopop"]},
    {"title":"但願人長久","artist":"鄧麗君","videoId":"D0LVKfWnIUQ","year":1978,"tags":["mandopop"]},
    {"title":"甜蜜蜜","artist":"鄧麗君","videoId":"DZmKWJYVHKs","year":1979,"tags":["mandopop"]},
    {"title":"漫步人生路","artist":"鄧麗君","videoId":"dG2_TfWWCEQ","year":1978,"tags":["mandopop"]},
    {"title":"一生想您","artist":"鄧麗君","videoId":"xH4RcwVLTdE","year":1979,"tags":["mandopop"]},
    {"title":"千千闋歌","artist":"鄧麗君","videoId":"gKP3fRQjfvE","year":1978,"tags":["mandopop"]},
    {"title":"似是故人來","artist":"梅艷芳","videoId":"P0Vb-_jHD7Q","year":1982,"tags":["cantopop"]},
    {"title":"朝代","artist":"徐克","videoId":"tJqM0kJBB6w","year":1977,"tags":["cantopop"]}
  ],
  "80s": [
    {"title":"Billie Jean","artist":"Michael Jackson","videoId":"Zi_XLOBDo_Y","year":1983,"tags":["pop"]},
    {"title":"Take On Me","artist":"a-ha","videoId":"djV11Xbc914","year":1985,"tags":["pop"]},
    {"title":"Sweet Child O' Mine","artist":"Guns N' Roses","videoId":"1w7OgIMMRc4","year":1987,"tags":["rock"]},
    {"title":"Like a Prayer","artist":"Madonna","videoId":"79fzeNUqQbQ","year":1989,"tags":["pop"]},
    {"title":"Africa","artist":"Toto","videoId":"FTQbiNvZqaY","year":1982,"tags":["rock"]},
    {"title":"Beat It","artist":"Michael Jackson","videoId":"oRdxUFDoQe0","year":1983,"tags":["pop"]},
    {"title":"Thriller","artist":"Michael Jackson","videoId":"sOnqjkJTMaA","year":1983,"tags":["pop"]},
    {"title":"Girls Just Want to Have Fun","artist":"Cyndi Lauper","videoId":"PIb6AZdTr-A","year":1983,"tags":["pop"]},
    {"title":"Careless Whisper","artist":"George Michael","videoId":"izGwDsrQ1eQ","year":1984,"tags":["pop"]},
    {"title":"Never Gonna Give You Up","artist":"Rick Astley","videoId":"dQw4w9WgXcQ","year":1987,"tags":["pop"]},
    {"title":"Eye of the Tiger","artist":"Survivor","videoId":"btPJPFnesV4","year":1982,"tags":["rock"]},
    {"title":"Livin' on a Prayer","artist":"Bon Jovi","videoId":"lDK9QqIzhwk","year":1986,"tags":["rock"]},
    {"title":"Time After Time","artist":"Cyndi Lauper","videoId":"VdQY7BusJNU","year":1984,"tags":["pop"]},
    {"title":"Take My Breath Away","artist":"Berlin","videoId":"Bx51eegLTY8","year":1986,"tags":["pop"]},
    {"title":"Hungry Like the Wolf","artist":"Duran Duran","videoId":"oJL-lCzEXgI","year":1982,"tags":["pop"]},
    {"title":"Karma Chameleon","artist":"Culture Club","videoId":"JmcA9LIIXWw","year":1983,"tags":["pop"]},
    {"title":"Flashdance... What a Feeling","artist":"Irene Cara","videoId":"ILWSp0m9G2U","year":1983,"tags":["pop"]},
    {"title":"Nothing's Gonna Stop Us Now","artist":"Starship","videoId":"3wxyN3z9PL4","year":1987,"tags":["pop"]},
    {"title":"Every Breath You Take","artist":"The Police","videoId":"OMOGaugKpzs","year":1983,"tags":["rock"]},
    {"title":"Wake Me Up Before You Go-Go","artist":"Wham!","videoId":"pIgZ7gMze7A","year":1984,"tags":["pop"]},
    {"title":"Jump","artist":"Van Halen","videoId":"SwZ_eW04pWQ","year":1984,"tags":["rock"]},
    {"title":"Total Eclipse of the Heart","artist":"Bonnie Tyler","videoId":"lcOxhH8N3He","year":1983,"tags":["rock"]},
    {"title":"Like a Virgin","artist":"Madonna","videoId":"sVh90UIBm44","year":1984,"tags":["pop"]},
    {"title":"Material Girl","artist":"Madonna","videoId":"AWHQF8BnyG0","year":1984,"tags":["pop"]},
    {"title":"Into the Groove","artist":"Madonna","videoId":"qXY4BKHKaQs","year":1985,"tags":["pop"]},
    {"title":"Vogue","artist":"Madonna","videoId":"FMvTdBL7gEY","year":1990,"tags":["pop"]},
    {"title":"Express Yourself","artist":"Madonna","videoId":"FwfFeO0xPyg","year":1989,"tags":["pop"]},
    {"title":"Waltz Darling","artist":"Pet Shop Boys","videoId":"XM_KBK_G-6s","year":1985,"tags":["pop"]},
    {"title":"It's My Life","artist":"Talk Talk","videoId":"T3KT7-lP7Wk","year":1984,"tags":["pop"]},
    {"title":"Down Under","artist":"Men at Work","videoId":"XfqHccJ-6Ls","year":1981,"tags":["pop"]},
    {"title":"Come On Eileen","artist":"Dexys Midnight Runners","videoId":"MZ8K2wVEUDc","year":1982,"tags":["pop"]},
    {"title":"Don't You (Forget About Me)","artist":"Simple Minds","videoId":"CaK_bVry4mE","year":1985,"tags":["rock"]},
    {"title":"Glory Days","artist":"Bruce Springsteen","videoId":"VFvb3GUwjOI","year":1984,"tags":["rock"]},
    {"title":"Born in the USA","artist":"Bruce Springsteen","videoId":"f2FZAHfnKMc","year":1984,"tags":["rock"]},
    {"title":"Dancing in the Sheets","artist":"Shalamar","videoId":"R8_7MYwNJXw","year":1984,"tags":["funk"]},
    {"title":"Footloose","artist":"Kenny Loggins","videoId":"EjCMpXxjNpE","year":1984,"tags":["pop"]},
    {"title":"Let's Dance","artist":"David Bowie","videoId":"hBuWbx-cJfE","year":1983,"tags":["rock"]},
    {"title":"Modern Love","artist":"David Bowie","videoId":"jqSQHWaYHgA","year":1985,"tags":["rock"]},
    {"title":"China Girl","artist":"David Bowie","videoId":"OL6gZ3gy-gU","year":1983,"tags":["rock"]},
    {"title":"Rebel Yell","artist":"Billy Idol","videoId":"sPzwo8jcAHs","year":1983,"tags":["rock"]},
    {"title":"Mister Sandman","artist":"The Chordettes","videoId":"_8YiSflDkSQ","year":1954,"tags":["pop"]},
    {"title":"Cum on Feel the Noize","artist":"Quiet Riot","videoId":"QtTfwqzIjSw","year":1983,"tags":["rock"]},
    {"title":"Barracuda","artist":"Heart","videoId":"0diJNybk0Mw","year":1977,"tags":["rock"]},
    {"title":"Love Shack","artist":"The B-52's","videoId":"9SOryJvTAGs","year":1989,"tags":["pop"]},
    {"title":"Mickey","artist":"Toni Basil","videoId":"bx1XB3-_kOU","year":1981,"tags":["pop"]},
    {"title":"99 Luftballons","artist":"Nena","videoId":"Eo-KmOd3i7s","year":1983,"tags":["rock"]},
    {"title":"Obsession","artist":"Animotion","videoId":"Pmme02CuM7c","year":1984,"tags":["pop"]},
    {"title":"I Just Called to Say I Love You","artist":"Stevie Wonder","videoId":"WQX-OzCqGu0","year":1984,"tags":["pop"]},
    {"title":"Endless Love","artist":"Diana Ross & Lionel Richie","videoId":"WP8OiBnhG4w","year":1981,"tags":["pop"]},
    {"title":"Against All Odds","artist":"Phil Collins","videoId":"MK0yXpTl9Pg","year":1984,"tags":["pop"]},
    {"title":"In Your Eyes","artist":"Peter Gabriel","videoId":"QQz0WdLpSns","year":1986,"tags":["pop"]},
    {"title":"Don't Give Up","artist":"Peter Gabriel & Kate Bush","videoId":"gKJTYVKZKhQ","year":1986,"tags":["pop"]},
    {"title":"Sledgehammer","artist":"Peter Gabriel","videoId":"OGGR0vfbIZE","year":1986,"tags":["pop"]},
    {"title":"Uptown Girl","artist":"Billy Joel","videoId":"kJQP7kiw5Fk","year":1983,"tags":["pop"]},
    {"title":"Piano Man","artist":"Billy Joel","videoId":"gxEPV4kolz0","year":1973,"tags":["pop"]},
    {"title":"Pressure","artist":"Billy Joel","videoId":"S6nR6KYmP9c","year":1982,"tags":["pop"]},
    {"title":"You're the Only Woman","artist":"Ambrosia","videoId":"iJnGYDlMNuQ","year":1980,"tags":["pop"]},
    {"title":"Blue Monday","artist":"New Order","videoId":"FYH8DsO4IDE","year":1983,"tags":["electronic"]},
    {"title":"Just Like Heaven","artist":"The Cure","videoId":"j6zksVLJMEo","year":1987,"tags":["rock"]},
    {"title":"Boys Don't Cry","artist":"The Cure","videoId":"4SuKLFHkdHg","year":1979,"tags":["rock"]},
    {"title":"Friday I'm in Love","artist":"The Cure","videoId":"ta-Z_psXgpE","year":1992,"tags":["rock"]},
    {"title":"Fascination","artist":"Company of Wolves","videoId":"MU9LAKGhwKQ","year":1985,"tags":["rock"]},
    {"title":"King of Pain","artist":"The Police","videoId":"OILx1_gWvFM","year":1985,"tags":["rock"]},
    {"title":"Wrapped Around Your Finger","artist":"The Police","videoId":"lnwp3OMwN5I","year":1983,"tags":["rock"]},
    {"title":"So Lonely","artist":"The Police","videoId":"wm7DvHWMXys","year":1978,"tags":["rock"]},
    {"title":"紅茶館","artist":"新寶島康樂隊","videoId":"T-3nDwHgLI8","year":1985,"tags":["cantopop"]},
    {"title":"一生想您","artist":"鄧麗君","videoId":"xH4RcwVLTdE","year":1985,"tags":["mandopop"]},
    {"title":"似是故人來","artist":"梅艷芳","videoId":"P0Vb-_jHD7Q","year":1982,"tags":["cantopop"]},
    {"title":"尋夢園","artist":"張國榮","videoId":"kFkdL8zIwHU","year":1986,"tags":["cantopop"]},
    {"title":"千千闋歌","artist":"鄧麗君","videoId":"gKP3fRQjfvE","year":1985,"tags":["mandopop"]},
    {"title":"我是不是該安靜地走開","artist":"鄧麗君","videoId":"m1Qua4Ps8gY","year":1980,"tags":["mandopop"]},
    {"title":"光輝歲月","artist":"Beyond","videoId":"oWrRKPqFu-w","year":1989,"tags":["cantopop"]},
    {"title":"農民","artist":"鄧麗君","videoId":"fq1_tLt9p9I","year":1985,"tags":["mandopop"]}
  ],
  "90s": [
    {"title":"Smells Like Teen Spirit","artist":"Nirvana","videoId":"hTWKbfoikeg","year":1991,"tags":["rock"]},
    {"title":"...Baby One More Time","artist":"Britney Spears","videoId":"C-u5WLJ9Yk4","year":1998,"tags":["pop"]},
    {"title":"No Scrubs","artist":"TLC","videoId":"FrLequ6dUdM","year":1999,"tags":["rnb"]},
    {"title":"Wonderwall","artist":"Oasis","videoId":"bx1Bh8ZvH84","year":1995,"tags":["rock"]},
    {"title":"My Heart Will Go On","artist":"Celine Dion","videoId":"FHG2oizTlpY","year":1997,"tags":["pop"]},
    {"title":"Vogue","artist":"Madonna","videoId":"GuJQSAiODqI","year":1990,"tags":["pop"]},
    {"title":"Losing My Religion","artist":"R.E.M.","videoId":"xwtdhWltSIg","year":1991,"tags":["rock"]},
    {"title":"Black or White","artist":"Michael Jackson","videoId":"F2AitTPI5U0","year":1991,"tags":["pop"]},
    {"title":"Creep","artist":"Radiohead","videoId":"XFkzRNyygfk","year":1992,"tags":["rock"]},
    {"title":"I Want It That Way","artist":"Backstreet Boys","videoId":"4fndeDfaWCg","year":1999,"tags":["pop"]},
    {"title":"Genie in a Bottle","artist":"Christina Aguilera","videoId":"kIDWgqDBNXA","year":1999,"tags":["pop"]},
    {"title":"Gangsta's Paradise","artist":"Coolio","videoId":"fPO76Jlnz6c","year":1995,"tags":["hiphop"]},
    {"title":"Waterfalls","artist":"TLC","videoId":"8WEtxJ4-sh4","year":1995,"tags":["rnb"]},
    {"title":"Say My Name","artist":"Destiny's Child","videoId":"sQgd6MccwZc","year":1999,"tags":["rnb"]},
    {"title":"Enter Sandman","artist":"Metallica","videoId":"CD-E-LDc384","year":1991,"tags":["rock"]},
    {"title":"Macarena","artist":"Los Del Rio","videoId":"zWaymcVmJ-A","year":1993,"tags":["latin"]},
    {"title":"Livin' la Vida Loca","artist":"Ricky Martin","videoId":"p47fEXGabaY","year":1999,"tags":["latin"]},
    {"title":"Torn","artist":"Natalie Imbruglia","videoId":"VV1XWJN3nJo","year":1997,"tags":["pop"]},
    {"title":"Iris","artist":"Goo Goo Dolls","videoId":"NdYWuo9OFAw","year":1998,"tags":["rock"]},
    {"title":"Baby Come On Over","artist":"Samantha Mumba","videoId":"Yd5g7JgMWks","year":1999,"tags":["pop"]},
    {"title":"Don't Look Back in Anger","artist":"Oasis","videoId":"cgoRfMpDArY","year":1996,"tags":["britpop"]},
    {"title":"Definitely Maybe","artist":"Oasis","videoId":"rC6DzgVnR2w","year":1994,"tags":["britpop"]},
    {"title":"Champagne Supernova","artist":"Oasis","videoId":"JLecoU5e0UI","year":1996,"tags":["britpop"]},
    {"title":"Song 2","artist":"Blur","videoId":"SSbBvKylVAc","year":1997,"tags":["britpop"]},
    {"title":"Parklife","artist":"Blur","videoId":"bVj69sLxH6s","year":1994,"tags":["britpop"]},
    {"title":"There's No Other Way","artist":"Blur","videoId":"cqSa7mGJnLo","year":1991,"tags":["britpop"]},
    {"title":"Girls & Boys","artist":"Blur","videoId":"aWQ_hVrKfWg","year":1994,"tags":["britpop"]},
    {"title":"Pulp Fiction","artist":"Pulp","videoId":"nrw1cLf0bTU","year":1994,"tags":["britpop"]},
    {"title":"Disco 2000","artist":"Pulp","videoId":"7mKWR0ecH8Q","year":1995,"tags":["britpop"]},
    {"title":"Common People","artist":"Pulp","videoId":"yuTMWQRJJOU","year":1995,"tags":["britpop"]},
    {"title":"Bitter Sweet Symphony","artist":"The Verve","videoId":"1lyu1KKwC18","year":1997,"tags":["britpop"]},
    {"title":"The Scientist","artist":"Coldplay","videoId":"EqWRaAF6_HC","year":2002,"tags":["britpop"]},
    {"title":"Yellow","artist":"Coldplay","videoId":"dvgZkm1xWPE","year":2000,"tags":["britpop"]},
    {"title":"Paradise City","artist":"Guns N' Roses","videoId":"Udx-BTu9qvE","year":1989,"tags":["rock"]},
    {"title":"Welcome to the Jungle","artist":"Guns N' Roses","videoId":"o1tj2zJ2Wh0","year":1988,"tags":["rock"]},
    {"title":"Knocking on Heaven's Door","artist":"Guns N' Roses","videoId":"WpqNgzmJT7g","year":1991,"tags":["rock"]},
    {"title":"Civil War","artist":"Guns N' Roses","videoId":"f6CjlehHAAI","year":1991,"tags":["rock"]},
    {"title":"More Than Words","artist":"Extreme","videoId":" inolJpXY8Go","year":1990,"tags":["rock"]},
    {"title":"Plowed","artist":"Phish","videoId":"oPQxPUIbr48","year":1994,"tags":["rock"]},
    {"title":"Dream On","artist":"Aerosmith","videoId":"TxCPj2mWEtU","year":1973,"tags":["rock"]},
    {"title":"Jeremy","artist":"Pearl Jam","videoId":"MS4VF2aHmWI","year":1991,"tags":["grunge"]},
    {"title":"Alive","artist":"Pearl Jam","videoId":"mtOGnvT-0yE","year":1991,"tags":["grunge"]},
    {"title":"Better Man","artist":"Pearl Jam","videoId":"xV7L5n-bVjw","year":1994,"tags":["grunge"]},
    {"title":"Black","artist":"Pearl Jam","videoId":"_RreFEykAFU","year":1991,"tags":["grunge"]},
    {"title":"Plush","artist":"Stone Temple Pilots","videoId":"Hh_Z2YDq0bc","year":1992,"tags":["grunge"]},
    {"title":"Rooster","artist":"Alice in Chains","videoId":"LFKjlzl6Tqk","year":1992,"tags":["grunge"]},
    {"title":"Man in the Box","artist":"Alice in Chains","videoId":"TAqXs_d4dKQ","year":1990,"tags":["grunge"]},
    {"title":"Lithium","artist":"Nirvana","videoId":"pmmhHpKYLXo","year":1992,"tags":["grunge"]},
    {"title":"Come as You Are","artist":"Nirvana","videoId":"_nI_0XNWkXE","year":1992,"tags":["grunge"]},
    {"title":"Heart-Shaped Box","artist":"Nirvana","videoId":"n6p-SxHj6CI","year":1993,"tags":["grunge"]},
    {"title":"Dude (Looks Like a Lady)","artist":"Aerosmith","videoId":"H-3_BSwIR90","year":1987,"tags":["rock"]},
    {"title":"Walk This Way","artist":"Aerosmith","videoId":"ZxVYXCVcXXE","year":1975,"tags":["rock"]},
    {"title":"Sad But True","artist":"Metallica","videoId":"A1ibeBAGJdA","year":1991,"tags":["metal"]},
    {"title":"The Unforgiven","artist":"Metallica","videoId":"VvKXpF0d5FQ","year":1991,"tags":["metal"]},
    {"title":"Nothing Else Matters","artist":"Metallica","videoId":"tAp9BKJe2NE","year":1991,"tags":["metal"]},
    {"title":"One","artist":"Metallica","videoId":"WM8bCaVQ11c","year":1989,"tags":["metal"]},
    {"title":"Fade to Black","artist":"Metallica","videoId":"7V0Tz-Rnfhg","year":1984,"tags":["metal"]},
    {"title":"Master of Puppets","artist":"Metallica","videoId":"bnKlJJD2qGo","year":1986,"tags":["metal"]},
    {"title":"Under the Bridge","artist":"Red Hot Chili Peppers","videoId":"gl8RF65jjMs","year":1991,"tags":["funk"]},
    {"title":"Give It Away","artist":"Red Hot Chili Peppers","videoId":"Mr_L-NfkQEI","year":1991,"tags":["funk"]},
    {"title":"Scar Tissue","artist":"Red Hot Chili Peppers","videoId":"mSepP2Chisz","year":1999,"tags":["funk"]},
    {"title":"Californication","artist":"Red Hot Chili Peppers","videoId":"YlUKcNNa2AI","year":1999,"tags":["funk"]},
    {"title":"By the Way","artist":"Red Hot Chili Peppers","videoId":"PO5-rl43Rho","year":2002,"tags":["funk"]},
    {"title":"一生想您","artist":"鄧麗君","videoId":"xH4RcwVLTdE","year":1995,"tags":["mandopop"]},
    {"title":"似是故人來","artist":"梅艷芳","videoId":"P0Vb-_jHD7Q","year":1992,"tags":["cantopop"]},
    {"title":"光輝歲月","artist":"Beyond","videoId":"oWrRKPqFu-w","year":1989,"tags":["cantopop"]},
    {"title":"真的愛你","artist":"Beyond","videoId":"7M1-6l_mczE","year":1990,"tags":["cantopop"]},
    {"title":"不再猶豫","artist":"Beyond","videoId":"4-4tKJvb0yk","year":1991,"tags":["cantopop"]},
    {"title":"海闊天空","artist":"Beyond","videoId":"H1B_sKzQ_4c","year":1993,"tags":["cantopop"]},
    {"title":"農民","artist":"鄧麗君","videoId":"fq1_tLt9p9I","year":1995,"tags":["mandopop"]},
    {"title":"漫步人生路","artist":"鄧麗君","videoId":"dG2_TfWWCEQ","year":1993,"tags":["mandopop"]}
  ],
  "00s": [
    {"title":"Hey Ya!","artist":"Outkast","videoId":"PWgvGjAhvIw","year":2003,"tags":["hiphop"]},
    {"title":"In the End","artist":"Linkin Park","videoId":"eVTXPUF4Oz4","year":2000,"tags":["rock"]},
    {"title":"Umbrella","artist":"Rihanna","videoId":"CvBfHwUxHIk","year":2007,"tags":["pop"]},
    {"title":"Hips Don't Lie","artist":"Shakira","videoId":"DUT5rEU6pqM","year":2006,"tags":["latin"]},
    {"title":"Yeah!","artist":"Usher","videoId":"GxBSyx85Kp8","year":2004,"tags":["rnb"]},
    {"title":"Toxic","artist":"Britney Spears","videoId":"LOZuxwVk7TU","year":2004,"tags":["pop"]},
    {"title":"Boulevard of Broken Dreams","artist":"Green Day","videoId":"Soa3gO7tL-c","year":2004,"tags":["rock"]},
    {"title":"Poker Face","artist":"Lady Gaga","videoId":"bESGLojNYSo","year":2008,"tags":["pop"]},
    {"title":"Bad Romance","artist":"Lady Gaga","videoId":"qrO4YZeyl0I","year":2009,"tags":["pop"]},
    {"title":"Mr. Brightside","artist":"The Killers","videoId":"gGdGFtwCNBE","year":2003,"tags":["rock"]},
    {"title":"Crazy","artist":"Gnarls Barkley","videoId":"bd2B6SjMh_w","year":2006,"tags":["soul"]},
    {"title":"Gold Digger","artist":"Kanye West","videoId":"6vwNcNOTVzY","year":2005,"tags":["hiphop"]},
    {"title":"Temperature","artist":"Sean Paul","videoId":"dW2MmuA1nI4","year":2005,"tags":["dancehall"]},
    {"title":"Beautiful Girls","artist":"Sean Kingston","videoId":"MrTz5xjmso4","year":2007,"tags":["pop"]},
    {"title":"American Boy","artist":"Estelle","videoId":"Ic5vxw3eijY","year":2008,"tags":["rnb"]},
    {"title":"Complicated","artist":"Avril Lavigne","videoId":"5NPBIwQyPWE","year":2002,"tags":["pop"]},
    {"title":"Gee","artist":"Girls' Generation","videoId":"U7mPqycQ0tQ","year":2009,"tags":["kpop"]},
    {"title":"Sorry Sorry","artist":"Super Junior","videoId":"x6QA3m58DQw","year":2009,"tags":["kpop"]},
    {"title":"Numb","artist":"Linkin Park","videoId":"kXYiU_JCYtU","year":2003,"tags":["rock"]},
    {"title":"Dilemma","artist":"Nelly","videoId":"8WYHDfJDPDc","year":2002,"tags":["hiphop"]},
    {"title":"Beautiful","artist":"Christina Aguilera","videoId":"eHnQcNvQ308","year":2002,"tags":["pop"]},
    {"title":"Without Me","artist":"Eminem","videoId":"X9FGRkqAQzE","year":2002,"tags":["hiphop"]},
    {"title":"Crazy in Love","artist":"Beyoncé","videoId":"ViwtNLUqkMY","year":2003,"tags":["pop"]},
    {"title":"Single Ladies","artist":"Beyoncé","videoId":"4M2Qaf2z9Zw","year":2008,"tags":["pop"]},
    {"title":"Halo","artist":"Beyoncé","videoId":"bnLlAcXcJFM","year":2008,"tags":["pop"]},
    {"title":"If U Seek Amy","artist":"Britney Spears","videoId":"cE6wxDqdX0s","year":2009,"tags":["pop"]},
    {"title":"Oops!... I Did It Again","artist":"Britney Spears","videoId":"CduA0TULnow","year":2000,"tags":["pop"]},
    {"title":"Womanizer","artist":"Britney Spears","videoId":"LbwRd9s_ZQo","year":2008,"tags":["pop"]},
    {"title":"Toxic (Remix)","artist":"Britney Spears","videoId":"LOZuxwVk7TU","year":2004,"tags":["pop"]},
    {"title":"Try Again","artist":"Aaliyah","videoId":"EpOjBfRFQeE","year":2000,"tags":["rnb"]},
    {"title":"No Scrubs (Album Version)","artist":"TLC","videoId":"FrLequ6dUdM","year":1999,"tags":["rnb"]},
    {"title":"Lose Yourself","artist":"Eminem","videoId":"_Yhyp-_hX2s","year":2002,"tags":["hiphop"]},
    {"title":"In Da Club","artist":"50 Cent","videoId":"5qm8PH4xAss","year":2003,"tags":["hiphop"]},
    {"title":"Hollaback Girl","artist":"Gwen Stefani","videoId":"Kgjkth-E_ZY","year":2005,"tags":["pop"]},
    {"title":"Hot in Herre","artist":"Nelly","videoId":"WZaEHjJp-TE","year":2002,"tags":["hiphop"]},
    {"title":"SexyBack","artist":"Justin Timberlake","videoId":"aMIpLlhXV8Q","year":2006,"tags":["pop"]},
    {"title":"Umbrella","artist":"Rihanna","videoId":"CvBfHwUxHIk","year":2007,"tags":["pop"]},
    {"title":"Bleeding Love","artist":"Leona Lewis","videoId":"G71J1KX2hkc","year":2007,"tags":["pop"]},
    {"title":"Viva la Vida","artist":"Coldplay","videoId":"dvgZkm1xWPE","year":2008,"tags":["rock"]},
    {"title":"Chasing Cars","artist":"Snow Patrol","videoId":"GemKqzILV7w","year":2004,"tags":["rock"]},
    {"title":"Use Somebody","artist":"Kings of Leon","videoId":"tjlAiMLl3Pg","year":2008,"tags":["rock"]},
    {"title":"Sex on Fire","artist":"Kings of Leon","videoId":"xXEJaJJqSME","year":2010,"tags":["rock"]},
    {"title":"Take Me Out","artist":"Franz Ferdinand","videoId":"sFfVZPE7dDY","year":2004,"tags":["rock"]},
    {"title":"Seven Nation Army","artist":"The White Stripes","videoId":"0J2QdDbelmY","year":2003,"tags":["rock"]},
    {"title":"Seven Nation Army (Glitch Mob Remix)","artist":"The White Stripes","videoId":"LVGH2pZXgYg","year":2003,"tags":["rock"]},
    {"title":"American Idiot","artist":"Green Day","videoId":"Ee_usTSKiF0","year":2004,"tags":["rock"]},
    {"title":"Wake Me Up When September Ends","artist":"Green Day","videoId":"4zISa50FWE0","year":2004,"tags":["rock"]},
    {"title":"Song 2","artist":"Blur","videoId":"SSbBvKylVAc","year":1997,"tags":["britpop"]},
    {"title":"Bring Me to Life","artist":"Evanescence","videoId":"3YxaaGgTQYM","year":2003,"tags":["rock"]},
    {"title":"My Immortal","artist":"Evanescence","videoId":"5anLPw0Efmo","year":2003,"tags":["rock"]},
    {"title":"Wake Me Up","artist":"Ed Sheeran","videoId":"OPf0YbXqDm0","year":2011,"tags":["pop"]},
    {"title":"Last Nite","artist":"The Strokes","videoId":"BjyxMO0nJ0c","year":2001,"tags":["rock"]},
    {"title":"Reptilia","artist":"The Strokes","videoId":"SVfIKgWNw80","year":2003,"tags":["rock"]},
    {"title":"Gold","artist":"Imagine Dragons","videoId":"D7BYOhAKrJc","year":2015,"tags":["rock"]},
    {"title":"Wonderwall (Piano Version)","artist":"Oasis","videoId":"bx1Bh8ZvH84","year":1995,"tags":["britpop"]},
    {"title":"Fix You","artist":"Coldplay","videoId":"k4V3di0D0l0","year":2005,"tags":["rock"]},
    {"title":"A Sky Full of Stars","artist":"Coldplay","videoId":"1lfBVv64qx0","year":2014,"tags":["rock"]},
    {"title":"Clocks","artist":"Coldplay","videoId":"D7BYOhAKrJc","year":2002,"tags":["rock"]},
    {"title":"Paradise","artist":"Coldplay","videoId":"1lfBVv64qx0","year":2011,"tags":["rock"]},
    {"title":"Me and You","artist":"Lifehouse","videoId":"h-i-BlZ_XP8","year":2005,"tags":["rock"]},
    {"title":"Smooth Criminal","artist":"Alien Ant Farm","videoId":"CDl9ZUvrgKY","year":2001,"tags":["rock"]},
    {"title":"Wonderwall (Studio Version)","artist":"Oasis","videoId":"bx1Bh8ZvH84","year":1995,"tags":["britpop"]},
    {"title":"呢喃細語","artist":"S.H.E","videoId":"Z9LzAKhPp3w","year":2001,"tags":["mandopop"]},
    {"title":"怪獸","artist":"S.H.E","videoId":"Yfg8m9TKzT4","year":2004,"tags":["mandopop"]},
    {"title":"中國話","artist":"S.H.E","videoId":"0jZZhB2f-2s","year":2003,"tags":["mandopop"]},
    {"title":"天亮了","artist":"韓紅","videoId":"aLNZkpzCvzc","year":2000,"tags":["mandopop"]},
    {"title":"雨一直下","artist":"五月天","videoId":"42Gt_kJ5z1w","year":2003,"tags":["mandopop"]},
    {"title":"志明與春嬌","artist":"陳奕迅","videoId":"j-oIRj3PX58","year":2005,"tags":["cantopop"]},
    {"title":"浮躁","artist":"陳奕迅","videoId":"HqzFhWYYV4M","year":2003,"tags":["cantopop"]},
    {"title":"十年","artist":"陳奕迅","videoId":"3EYqMDHt9z4","year":2003,"tags":["cantopop"]},
    {"title":"K歌之王","artist":"陳奕迅","videoId":"IxVevGlGYSc","year":2000,"tags":["cantopop"]},
    {"title":"一生想您","artist":"鄧麗君","videoId":"xH4RcwVLTdE","year":2000,"tags":["mandopop"]}
  ],
  "10s": [
    {"title":"Rolling in the Deep","artist":"Adele","videoId":"rYEDA3JcQqw","year":2010,"tags":["pop"]},
    {"title":"Uptown Funk","artist":"Mark Ronson ft. Bruno Mars","videoId":"OPf0YbXqDm0","year":2014,"tags":["funk"]},
    {"title":"Shape of You","artist":"Ed Sheeran","videoId":"JGwWNGJdvx8","year":2017,"tags":["pop"]},
    {"title":"Bad Guy","artist":"Billie Eilish","videoId":"DyDfgMOUjCI","year":2019,"tags":["pop"]},
    {"title":"Gangnam Style","artist":"PSY","videoId":"9bZkp7q19f0","year":2012,"tags":["kpop"]},
    {"title":"Sorry","artist":"Justin Bieber","videoId":"fRh_vgS2dFE","year":2015,"tags":["pop"]},
    {"title":"Hello","artist":"Adele","videoId":"YQHsXMglC9A","year":2015,"tags":["pop"]},
    {"title":"Roar","artist":"Katy Perry","videoId":"CevxZvSJLk8","year":2013,"tags":["pop"]},
    {"title":"Blank Space","artist":"Taylor Swift","videoId":"e-ORhEE9VVg","year":2014,"tags":["pop"]},
    {"title":"Lean On","artist":"Major Lazer","videoId":"YqeW9_5kURI","year":2015,"tags":["edm"]},
    {"title":"Despacito","artist":"Luis Fonsi","videoId":"kJQP7kiw5Fk","year":2017,"tags":["latin"]},
    {"title":"Counting Stars","artist":"OneRepublic","videoId":"hT_nvWreIhg","year":2013,"tags":["pop"]},
    {"title":"Closer","artist":"The Chainsmokers","videoId":"PT2_F-1esPk","year":2016,"tags":["edm"]},
    {"title":"This Is America","artist":"Childish Gambino","videoId":"VYOjWnS4cMY","year":2018,"tags":["hiphop"]},
    {"title":"DNA","artist":"BTS","videoId":"MBdVXkSdhwU","year":2017,"tags":["kpop"]},
    {"title":"Faded","artist":"Alan Walker","videoId":"60ItHLz5WEA","year":2015,"tags":["edm"]},
    {"title":"Let Her Go","artist":"Passenger","videoId":"RBumgq5yVrA","year":2012,"tags":["pop"]},
    {"title":"Take Me to Church","artist":"Hozier","videoId":"PVjiKRfKpPI","year":2013,"tags":["indie"]},
    {"title":"Havana","artist":"Camila Cabello","videoId":"HCjNJDNzw8Y","year":2017,"tags":["pop"]},
    {"title":"Wake Me Up","artist":"Avicii","videoId":"IcrbM1l_BoI","year":2013,"tags":["edm"]},
    {"title":"I Love You","artist":"Billie Eilish","videoId":"HqB1ZjLT5Ew","year":2019,"tags":["pop"]},
    {"title":"We Don't Talk About Bruno","artist":"Encanto","videoId":"bvWRMAU6V-c","year":2021,"tags":["pop"]},
    {"title":"Mirrors","artist":"Justin Timberlake","videoId":"mMKoq5y2-lE","year":2013,"tags":["pop"]},
    {"title":"As Long as You Love Me","artist":"Justin Bieber","videoId":"qh2h5YjW_hE","year":2012,"tags":["pop"]},
    {"title":"Boyfriend","artist":"Justin Bieber","videoId":"jUIGpMiVnE4","year":2012,"tags":["pop"]},
    {"title":"Take Back the Night","artist":"Justin Timberlake","videoId":"K-dBl1ePx1c","year":2013,"tags":["pop"]},
    {"title":"Suit & Tie","artist":"Justin Timberlake","videoId":"Mc0iiBXDAkk","year":2013,"tags":["pop"]},
    {"title":"Blurred Lines","artist":"Robin Thicke","videoId":"yrQ6dV3O5TM","year":2013,"tags":["pop"]},
    {"title":"Problem","artist":"Ariana Grande","videoId":"Io-S7hcb7gw","year":2014,"tags":["pop"]},
    {"title":"Break Free","artist":"Ariana Grande","videoId":"Ixo4e6Zs_nI","year":2014,"tags":["pop"]},
    {"title":"Bang Bang","artist":"Ariana Grande","videoId":"0DiMHbF_gMw","year":2014,"tags":["pop"]},
    {"title":"Love Me Like You Do","artist":"Ellie Goulding","videoId":"xA-pFKbIH8A","year":2014,"tags":["pop"]},
    {"title":"Lights","artist":"Ellie Goulding","videoId":"F0Gb5NWLJ58","year":2011,"tags":["pop"]},
    {"title":"Burn","artist":"Ellie Goulding","videoId":"nlcIKh6sBtc","year":2013,"tags":["pop"]},
    {"title":"I'm Not The Only One","artist":"Sam Smith","videoId":"xJ1HnPwhv5o","year":2014,"tags":["pop"]},
    {"title":"I'm In Love With The Coco","artist":"O.T. Genasis","videoId":"f8BbVSB8s08","year":2013,"tags":["hiphop"]},
    {"title":"Thinking Out Loud","artist":"Ed Sheeran","videoId":"aI5TkH4XrXo","year":2014,"tags":["pop"]},
    {"title":"Sing","artist":"Ed Sheeran","videoId":"yp0ZhgEYoMI","year":2014,"tags":["pop"]},
    {"title":"Lego House","artist":"Ed Sheeran","videoId":"NvKpw-2LiWg","year":2011,"tags":["pop"]},
    {"title":"Castle on the Hill","artist":"Ed Sheeran","videoId":"K0ibBPhbMn0","year":2017,"tags":["pop"]},
    {"title":"Divide","artist":"Ed Sheeran","videoId":"p4FDz_XqDvw","year":2017,"tags":["pop"]},
    {"title":"Galway Girl","artist":"Ed Sheeran","videoId":"PiPjWyJJx0c","year":2017,"tags":["pop"]},
    {"title":"I See Fire","artist":"Ed Sheeran","videoId":"4MrYCPvEAXE","year":2013,"tags":["pop"]},
    {"title":"Happier","artist":"Ed Sheeran","videoId":"K0ibBPhbMn0","year":2017,"tags":["pop"]},
    {"title":"Shivers","artist":"Ed Sheeran","videoId":"j-PypNGqAqE","year":2021,"tags":["pop"]},
    {"title":"Perfect","artist":"Ed Sheeran","videoId":"nSDgHBwacFI","year":2014,"tags":["pop"]},
    {"title":"Thinking Out Loud","artist":"Ed Sheeran","videoId":"aI5TkH4XrXo","year":2014,"tags":["pop"]},
    {"title":"Supermodel","artist":"RuPaul","videoId":"GhOkb1_v0CY","year":2014,"tags":["pop"]},
    {"title":"Chandelier","artist":"Sia","videoId":"2vjPBrBU-TM","year":2013,"tags":["pop"]},
    {"title":"Cheap Thrills","artist":"Sia","videoId":"nYh-n7iWmV0","year":2015,"tags":["pop"]},
    {"title":"Breathe","artist":"Sia","videoId":"HV-5lPZ7bgE","year":2013,"tags":["pop"]},
    {"title":"Black","artist":"Black Eyed Peas","videoId":"bXUaGZY6aMI","year":2010,"tags":["hiphop"]},
    {"title":"Don't Phunk With My Heart","artist":"Black Eyed Peas","videoId":"LKxB4aONHuY","year":2005,"tags":["hiphop"]},
    {"title":"Where Them Girls At","artist":"David Guetta","videoId":"mYmn2z_xJo8","year":2011,"tags":["edm"]},
    {"title":"Titanium","artist":"David Guetta","videoId":"JYIaFekhc0s","year":2011,"tags":["edm"]},
    {"title":"Turn Down for What","artist":"DJ Snake & Lil Jon","videoId":"ZkZSJME96Kg","year":2013,"tags":["edm"]},
    {"title":"One Kiss","artist":"Calvin Harris & Dua Lipa","videoId":"tYzd0mDqkC0","year":2018,"tags":["edm"]},
    {"title":"Electricity","artist":"Mark Ronson","videoId":"K2cYWfq--Nw","year":2018,"tags":["funk"]},
    {"title":"Uptown Special","artist":"Mark Ronson","videoId":"TqKPq6gWpCM","year":2015,"tags":["funk"]},
    {"title":"As Long As You Love Me","artist":"Justin Bieber","videoId":"qh2h5YjW_hE","year":2012,"tags":["pop"]},
    {"title":"Tik Tok","artist":"Kesha","videoId":"iP6E2H_PmKA","year":2009,"tags":["pop"]},
    {"title":"Can't Hold Us","artist":"Macklemore & Ryan Lewis","videoId":"2zYvbwAP6-w","year":2011,"tags":["hiphop"]},
    {"title":"Thrift Shop","artist":"Macklemore & Ryan Lewis","videoId":"QK8mJJJvM04","year":2012,"tags":["hiphop"]},
    {"title":"Downtown","artist":"Macklemore & Ryan Lewis","videoId":"BXM41Sm6ZfQ","year":2012,"tags":["hiphop"]},
    {"title":"Fight Song","artist":"Rachel Platten","videoId":"xo1VJV_ls-k","year":2014,"tags":["pop"]},
    {"title":"讚佩","artist":"劉浩龍","videoId":"8hG-oXPl4Hs","year":2010,"tags":["cantopop"]},
    {"title":"光輝歲月","artist":"Beyond","videoId":"H1B_sKzQ_4c","year":2010,"tags":["cantopop"]},
    {"title":"講好愛你","artist":"曾愛","videoId":"v5KpqeIU8hY","year":2012,"tags":["cantopop"]},
    {"title":"一千個傷心的理由","artist":"張學友","videoId":"WQVQVmFr1OI","year":2012,"tags":["cantopop"]},
    {"title":"K歌之王","artist":"陳奕迅","videoId":"IxVevGlGYSc","year":2010,"tags":["cantopop"]},
    {"title":"光年之外","artist":"鄧紫棋","videoId":"2sXNaLrGLe4","year":2017,"tags":["mandopop"]},
    {"title":"光年之外 (Live)","artist":"鄧紫棋","videoId":"Y3Cq7gHhE8s","year":2017,"tags":["mandopop"]},
    {"title":"光芒","artist":"鄧紫棋","videoId":"n63nfjQJZBg","year":2014,"tags":["mandopop"]},
    {"title":"光伏板","artist":"Fiona Apple","videoId":"4-4tKJvb0yk","year":2012,"tags":["mandopop"]}
  ],
  "20s": [
    {"title":"Blinding Lights","artist":"The Weeknd","videoId":"4NRXx6U8ABQ","year":2020,"tags":["pop"]},
    {"title":"As It Was","artist":"Harry Styles","videoId":"H5v3kku4y6Q","year":2022,"tags":["pop"]},
    {"title":"Flowers","artist":"Miley Cyrus","videoId":"G7KNmW9a75Y","year":2023,"tags":["pop"]},
    {"title":"Anti-Hero","artist":"Taylor Swift","videoId":"b1kbLwvqugk","year":2022,"tags":["pop"]},
    {"title":"Espresso","artist":"Sabrina Carpenter","videoId":"eVli-tstM5E","year":2024,"tags":["pop"]},
    {"title":"Stay","artist":"The Kid LAROI & Justin Bieber","videoId":"kTJczUoc26U","year":2021,"tags":["pop"]},
    {"title":"Levitating","artist":"Dua Lipa","videoId":"TUVcZfQe-Kw","year":2020,"tags":["pop"]},
    {"title":"Peaches","artist":"Justin Bieber","videoId":"tQ0yjYUFKAE","year":2021,"tags":["pop"]},
    {"title":"Watermelon Sugar","artist":"Harry Styles","videoId":"E07s5ZYygMg","year":2020,"tags":["pop"]},
    {"title":"Butter","artist":"BTS","videoId":"WMweEpGlu_U","year":2021,"tags":["kpop"]},
    {"title":"Pink Venom","artist":"BLACKPINK","videoId":"gQlMMD8auMs","year":2022,"tags":["kpop"]},
    {"title":"Unholy","artist":"Sam Smith","videoId":"Uq9gPaIzbe8","year":2022,"tags":["pop"]},
    {"title":"good 4 u","artist":"Olivia Rodrigo","videoId":"gNi_6U5Pm_o","year":2021,"tags":["pop"]},
    {"title":"Drivers License","artist":"Olivia Rodrigo","videoId":"ZmDBbnmKpqQ","year":2021,"tags":["pop"]},
    {"title":"Easy On Me","artist":"Adele","videoId":"U3ASj1L6_sY","year":2021,"tags":["pop"]},
    {"title":"Paint The Town Red","artist":"Doja Cat","videoId":"m4_9TFeMfJE","year":2023,"tags":["hiphop"]},
    {"title":"Calm Down","artist":"Rema","videoId":"WcIcVapfqXw","year":2022,"tags":["afrobeats"]},
    {"title":"Seven","artist":"Jungkook","videoId":"QU9c0053UAU","year":2023,"tags":["kpop"]},
    {"title":"Super Shy","artist":"NewJeans","videoId":"ArmDp-zijuc","year":2023,"tags":["kpop"]},
    {"title":"Houdini","artist":"Dua Lipa","videoId":"suAR1PYFNYA","year":2023,"tags":["pop"]},
    {"title":"Heat Waves","artist":"Glass Animals","videoId":"0d0p4IqxJvY","year":2020,"tags":["rock"]},
    {"title":"Lovers","artist":"Justin Bieber","videoId":"_nI_0XNWkXE","year":2021,"tags":["pop"]},
    {"title":"Kiss Me","artist":"Sixpence None the Richer","videoId":"C0rwJGI_cj0","year":1999,"tags":["indie"]},
    {"title":"Sour Times","artist":"Portishead","videoId":"V0dHJ-lD-cA","year":1994,"tags":["trip_hop"]},
    {"title":"Teardrop","artist":"Massive Attack","videoId":"MvqH4mM7JtY","year":1998,"tags":["trip_hop"]},
    {"title":"Breathe In The Air","artist":"Pink Floyd","videoId":"hM-27tJPvqw","year":1973,"tags":["rock"]},
    {"title":"Song 2","artist":"Blur","videoId":"SSbBvKylVAc","year":1997,"tags":["britpop"]},
    {"title":"Wonderwall","artist":"Oasis","videoId":"bx1Bh8ZvH84","year":1995,"tags":["britpop"]},
    {"title":"Common People","artist":"Pulp","videoId":"yuTMWQRJJOU","year":1995,"tags":["britpop"]},
    {"title":"Don't Look Back in Anger","artist":"Oasis","videoId":"cgoRfMpDArY","year":1996,"tags":["britpop"]},
    {"title":"Wonderwall (Acoustic)","artist":"Oasis","videoId":"bx1Bh8ZvH84","year":1995,"tags":["britpop"]},
    {"title":"Wonderwall (Live)","artist":"Oasis","videoId":"bx1Bh8ZvH84","year":1995,"tags":["britpop"]},
    {"title":"Bitter Sweet Symphony","artist":"The Verve","videoId":"1lyu1KKwC18","year":1997,"tags":["britpop"]},
    {"title":"Achilles Last Stand","artist":"Led Zeppelin","videoId":"HQmmjptKCwY","year":1975,"tags":["rock"]},
    {"title":"Stairway to Heaven","artist":"Led Zeppelin","videoId":"fsH1XhTDcUc","year":1971,"tags":["rock"]},
    {"title":"Whole Lotta Love","artist":"Led Zeppelin","videoId":"HQmmjptKCwY","year":1969,"tags":["rock"]},
    {"title":"Black Dog","artist":"Led Zeppelin","videoId":"RbbxdVXVeAw","year":1971,"tags":["rock"]},
    {"title":"Immigrant Song","artist":"Led Zeppelin","videoId":"T_D8HqxKjhM","year":1970,"tags":["rock"]},
    {"title":"Good as Hell","artist":"Lizzo","videoId":"Nol6xIJbmSM","year":2016,"tags":["pop"]},
    {"title":"About Damn Time","artist":"Lizzo","videoId":"8CIBBA4Uw0A","year":2022,"tags":["pop"]},
    {"title":"Juice","artist":"Lizzo","videoId":"dsx2vTDU_cY","year":2019,"tags":["pop"]},
    {"title":"Truth Hurts","artist":"Lizzo","videoId":"POh4bqMPt_U","year":2017,"tags":["pop"]},
    {"title":"Rain On Me","artist":"Lady Gaga & Ariana Grande","videoId":"Uo1LqAJKg2k","year":2020,"tags":["pop"]},
    {"title":"Stupid Love","artist":"Lady Gaga","videoId":"dQw4w9WgXcQ","year":2020,"tags":["pop"]},
    {"title":"Chromatica II","artist":"Lady Gaga","videoId":"Pzb-sE3U4wg","year":2020,"tags":["pop"]},
    {"title":"Free Woman","artist":"Lady Gaga","videoId":"W7DnK9qL1B0","year":2020,"tags":["pop"]},
    {"title":"Plastics","artist":"Lady Gaga","videoId":"WTBndEjVW_4","year":2020,"tags":["pop"]},
    {"title":"Dua Lipa","artist":"Dua Lipa","videoId":"XUU-E1CZXcc","year":2020,"tags":["pop"]},
    {"title":"Don't Start Now","artist":"Dua Lipa","videoId":"SModm2sKcZM","year":2019,"tags":["pop"]},
    {"title":"Break My Heart","artist":"Dua Lipa","videoId":"KCAVD2FRnHQ","year":2020,"tags":["pop"]},
    {"title":"Lockdown","artist":"Anderson .Paak","videoId":"dQw4w9WgXcQ","year":2021,"tags":["soul"]},
    {"title":"Come & Go","artist":"Juice WRLD","videoId":"Gx8wrpeCMZA","year":2018,"tags":["hiphop"]},
    {"title":"Lucid Dreams","artist":"Juice WRLD","videoId":"mzB1VGEGcSY","year":2018,"tags":["hiphop"]},
    {"title":"Sunroof","artist":"Nicky Youre","videoId":"dQw4w9WgXcQ","year":2023,"tags":["indie"]},
    {"title":"Flowers (Remix)","artist":"Miley Cyrus","videoId":"G7KNmW9a75Y","year":2023,"tags":["pop"]},
    {"title":"Vampire","artist":"Olivia Rodrigo","videoId":"dQw4w9WgXcQ","year":2023,"tags":["pop"]},
    {"title":"Void","artist":"Olivia Rodrigo","videoId":"dQw4w9WgXcQ","year":2023,"tags":["pop"]},
    {"title":"All The Stars","artist":"Kendrick Lamar","videoId":"dQw4w9WgXcQ","year":2017,"tags":["hiphop"]},
    {"title":"HUMBLE","artist":"Kendrick Lamar","videoId":"tvTRZJ-4EyI","year":2017,"tags":["hiphop"]},
    {"title":"DNA","artist":"Kendrick Lamar","videoId":"NLZRYQMLDW4","year":2017,"tags":["hiphop"]},
    {"title":"PRIDE","artist":"Kendrick Lamar","videoId":"eHc9gYH-1yA","year":2017,"tags":["hiphop"]},
    {"title":"FEAR","artist":"Kendrick Lamar","videoId":"lRYlZN6p9yg","year":2017,"tags":["hiphop"]},
    {"title":"光年之外","artist":"鄧紫棋","videoId":"2sXNaLrGLe4","year":2020,"tags":["mandopop"]},
    {"title":"光","artist":"鄧紫棋","videoId":"lEk52TKMVFA","year":2021,"tags":["mandopop"]},
    {"title":"光芒","artist":"鄧紫棋","videoId":"n63nfjQJZBg","year":2020,"tags":["mandopop"]},
    {"title":"光影","artist":"鄧紫棋","videoId":"5-TdNq5dPvY","year":2022,"tags":["mandopop"]},
    {"title":"光臨","artist":"鄧紫棋","videoId":"wGY0pFNPO4E","year":2020,"tags":["mandopop"]},
    {"title":"光伏板","artist":"鄧紫棋","videoId":"WFO1d4Tz5Ys","year":2021,"tags":["mandopop"]},
    {"title":"光榮","artist":"鄧紫棋","videoId":"xQCLDGZy_6M","year":2022,"tags":["mandopop"]},
    {"title":"光陰","artist":"鄧紫棋","videoId":"jMNyJDLHFgw","year":2021,"tags":["mandopop"]}
  ]
}

export function getRandomVideo(decade: Decade, history: string[]): VideoEntry {
  const list = videos[decade]
  const filtered = list.filter((v) => !history.includes(v.videoId))
  const pool = filtered.length ? filtered : list
  return pool[Math.floor(Math.random() * pool.length)]
}
