export interface VideoEntry {
  title: string
  artist: string
  videoId: string
  year: number
  tags: string[]
}

export type Decade = '60s' | '70s' | '80s' | '90s' | '00s' | '10s' | '20s'

export const videos: Record<Decade, VideoEntry[]> = {
  "60s": [
    {"title":"Can't Help Falling in Love","artist":"Elvis Presley","videoId":"vGJTaP6anOU","year":1961,"tags":["pop"]},
    {"title":"I Want to Hold Your Hand","artist":"The Beatles","videoId":"jenWdylTtzs","year":1963,"tags":["rock"]},
    {"title":"Respect","artist":"Aretha Franklin","videoId":"6FOUqQt3Kg0","year":1967,"tags":["soul"]},
    {"title":"Stand By Me","artist":"Ben E. King","videoId":"hwZNL7QVJjE","year":1961,"tags":["soul"]},
    {"title":"My Girl","artist":"The Temptations","videoId":"qEztui18cA8","year":1964,"tags":["motown"]},
    {"title":"California Dreamin'","artist":"The Mamas & the Papas","videoId":"N-aK6JnyFmk","year":1965,"tags":["folk"]},
    {"title":"Paint It Black","artist":"The Rolling Stones","videoId":"O4irXQhgMqg","year":1966,"tags":["rock"]},
    {"title":"Light My Fire","artist":"The Doors","videoId":"qoX6AKuYWL8","year":1967,"tags":["rock"]},
    {"title":"Good Vibrations","artist":"The Beach Boys","videoId":"Eab_beh07HU","year":1966,"tags":["pop"]},
    {"title":"Come Together","artist":"The Beatles","videoId":"45cYwDMibGo","year":1969,"tags":["rock"]},
    {"title":"These Boots Are Made for Walkin'","artist":"Nancy Sinatra","videoId":"SbyAZQ45uww","year":1966,"tags":["pop"]},
    {"title":"A Whiter Shade of Pale","artist":"Procol Harum","videoId":"Mb3iPP-tHdA","year":1967,"tags":["rock"]},
    {"title":"The Sound of Silence","artist":"Simon & Garfunkel","videoId":"4zLfCnGVeL4","year":1965,"tags":["folk"]},
    {"title":"Sugar Sugar","artist":"The Archies","videoId":"h9nE2spOw_o","year":1969,"tags":["pop"]},
    {"title":"Surfin' USA","artist":"The Beach Boys","videoId":"EDb303T-B1w","year":1963,"tags":["pop"]},
    {"title":"Twist and Shout","artist":"The Beatles","videoId":"2RicaUqd9Hg","year":1963,"tags":["rock"]},
    {"title":"Be My Baby","artist":"The Ronettes","videoId":"jSPpbOGnFgk","year":1963,"tags":["pop"]},
    {"title":"Runaway","artist":"Del Shannon","videoId":"0S13mP_pfEc","year":1961,"tags":["rock"]},
    {"title":"I Heard It Through the Grapevine","artist":"Marvin Gaye","videoId":"cXWHpbpNdHE","year":1968,"tags":["soul"]},
    {"title":"Piece of My Heart","artist":"Janis Joplin","videoId":"SCngPse1iiI","year":1968,"tags":["rock"]},
    {"title":"Hound Dog","artist":"Elvis Presley","videoId":"-eHJ12Vhpyc","year":1956,"tags":["rock"]},
    {"title":"Johnny B. Goode","artist":"Chuck Berry","videoId":"Y-9Y4CCIWnM","year":1958,"tags":["rock"]},
    {"title":"Louie Louie","artist":"The Kingsmen","videoId":"xKt75jUuKJY","year":1963,"tags":["rock"]},
    {"title":"Satisfaction","artist":"The Rolling Stones","videoId":"nrIPxlFzDi0","year":1965,"tags":["rock"]},
    {"title":"Mony Mony","artist":"Tommy James","videoId":"qdrx9F6WEzM","year":1968,"tags":["pop"]},
    {"title":"She Loves You","artist":"The Beatles","videoId":"nGbWU8S3vzs","year":1963,"tags":["rock"]},
    {"title":"Itsy Bitsy Teenie Weenie Yellow Polka Dot Bikini","artist":"Brian Hyland","videoId":"gGUAI5FP-C0","year":1960,"tags":["pop"]},
    {"title":"Build Me Up Buttercup","artist":"The Foundations","videoId":"hSofzQURQDk","year":1968,"tags":["soul"]},
    {"title":"Mrs. Brown, You've Got a Lovely Daughter","artist":"Herman's Hermits","videoId":"kYYqZOH-Wl4","year":1965,"tags":["pop"]},
    {"title":"Help!","artist":"The Beatles","videoId":"2Q_ZzBGPdqE","year":1965,"tags":["rock"]},
    {"title":"Hang On Sloopy","artist":"The McCoys","videoId":"Nuw8GJbqx94","year":1965,"tags":["rock"]},
    {"title":"Downtown","artist":"Petula Clark","videoId":"cieS-GgnV7Q","year":1964,"tags":["pop"]},
    {"title":"I'm Telling You Now","artist":"Freddie & The Dreamers","videoId":"ALR13MJLAs4","year":1964,"tags":["pop"]},
    {"title":"Woolly Bully","artist":"Sam the Sham","videoId":"3UttAR8DnFY","year":1965,"tags":["rock"]},
    {"title":"Wild Thing","artist":"The Troggs","videoId":"bLJkrOYHNw8","year":1966,"tags":["rock"]},
    {"title":"Sunshine Superman","artist":"Donovan","videoId":"YsX2FhBf9nY","year":1966,"tags":["folk"]},
    {"title":"Time Is on My Side","artist":"The Rolling Stones","videoId":"ZHKz7FBUF1w","year":1964,"tags":["rock"]},
    {"title":"Norwegian Wood","artist":"The Beatles","videoId":"Y_V6y1ZCg_8","year":1965,"tags":["rock"]},
    {"title":"I Feel Fine","artist":"The Beatles","videoId":"WrAV5EVI4tU","year":1964,"tags":["rock"]},
    {"title":"I Got You Babe","artist":"Sonny & Cher","videoId":"HKGjCPBSG38","year":1965,"tags":["pop"]},
    {"title":"Where Did Our Love Go","artist":"The Supremes","videoId":"Jt_31gR18NA","year":1964,"tags":["soul"]},
    {"title":"Stop! In the Name of Love","artist":"The Supremes","videoId":"une981B7Q4Y","year":1965,"tags":["soul"]},
    {"title":"You Can't Hurry Love","artist":"The Supremes","videoId":"dXrvHakZLaw","year":1966,"tags":["soul"]},
    {"title":"Reach Out I'll Be There","artist":"Four Tops","videoId":"-rU2IBWDo2s","year":1966,"tags":["soul"]},
    {"title":"I Heard It Through the Grapevine (Gladys Knight)","artist":"Gladys Knight","videoId":"SFjJLMHRHFI","year":1967,"tags":["soul"]},
    {"title":"Proud Mary","artist":"Creedence Clearwater Revival","videoId":"8quvq_GFEbQ","year":1968,"tags":["rock"]},
    {"title":"Have You Ever Seen the Rain","artist":"Creedence Clearwater Revival","videoId":"u1V8YRJnr4Q","year":1970,"tags":["rock"]},
    {"title":"Green River","artist":"Creedence Clearwater Revival","videoId":"3WbmBK9BR9U","year":1969,"tags":["rock"]},
    {"title":"Bad Moon Rising","artist":"Creedence Clearwater Revival","videoId":"qrP5IClb6b8","year":1969,"tags":["rock"]},
    {"title":"House of the Rising Sun","artist":"The Animals","videoId":"PqW4GCmQSt4","year":1964,"tags":["rock"]},
    {"title":"Black Magic Woman","artist":"Santana","videoId":"9wT1s96JIb0","year":1968,"tags":["rock"]},
    {"title":"Do You Wanna Dance","artist":"Bobby Freeman","videoId":"sLwxTYYZJS0","year":1958,"tags":["rock"]},
    {"title":"Let's Twist Again","artist":"Chubby Checker","videoId":"Frw7U5X8dhg","year":1961,"tags":["pop"]},
    {"title":"Shout","artist":"The Isley Brothers","videoId":"DPVf01jXL7M","year":1959,"tags":["soul"]},
    {"title":"Land of 1000 Dances","artist":"Wilson Pickett","videoId":"QW2XeRqkcL0","year":1966,"tags":["soul"]},
    {"title":"Uptight (Everything's Alright)","artist":"Stevie Wonder","videoId":"QPjQxeG8tCo","year":1966,"tags":["soul"]},
    {"title":"For Once in My Life","artist":"Stevie Wonder","videoId":"l3qi3E40aWE","year":1968,"tags":["soul"]},
    {"title":"My World Is Empty Without You","artist":"The Supremes","videoId":"a3YWNsHOz8U","year":1965,"tags":["soul"]},
    {"title":"Dancing in the Street","artist":"Martha and the Vandellas","videoId":"M4p9qXIWN2Q","year":1964,"tags":["soul"]},
    {"title":"Money (That's What I Want)","artist":"Barrett Strong","videoId":"oU_ixZv9N-E","year":1959,"tags":["soul"]},
    {"title":"Venus","artist":"Shocking Blue","videoId":"aPEhQugz-Ew","year":1969,"tags":["pop"]},
    {"title":"Unchained Melody","artist":"The Righteous Brothers","videoId":"te51eVrFWEc","year":1965,"tags":["soul"]},
    {"title":"Georgia on My Mind","artist":"Ray Charles","videoId":"ggGzE5KfCio","year":1960,"tags":["soul"]},
    {"title":"Unforgettable","artist":"Nat King Cole","videoId":"iF7kOq0peAU","year":1951,"tags":["soul"]},
    {"title":"Dream a Little Dream of Me","artist":"Ella Fitzgerald","videoId":"wSKWoQAbPj8","year":1931,"tags":["jazz"]},
    {"title":"Moon River","artist":"Henry Mancini","videoId":"Ozg3P3LrJs8","year":1961,"tags":["easy"]},
    {"title":"Catch a Wave","artist":"The Beach Boys","videoId":"X_CBWxmTlRI","year":1963,"tags":["pop"]},
    {"title":"Barbara Ann","artist":"The Beach Boys","videoId":"4wvx14Qv9cg","year":1965,"tags":["pop"]},
    {"title":"Wouldn't It Be Nice","artist":"The Beach Boys","videoId":"5lP8BZcyoEQ","year":1966,"tags":["pop"]},
    {"title":"God Only Knows","artist":"The Beach Boys","videoId":"NADx3-qRxek","year":1966,"tags":["pop"]},
    {"title":"Help Me Rhonda","artist":"The Beach Boys","videoId":"JaHAf0fFp6A","year":1965,"tags":["pop"]},
    {"title":"I Walk the Line","artist":"Johnny Cash","videoId":"1JU_simUTVI","year":1956,"tags":["country"]},
    {"title":"Folsom Prison Blues","artist":"Johnny Cash","videoId":"AeZRYhLDLeU","year":1955,"tags":["country"]},
    {"title":"Ring of Fire","artist":"Johnny Cash","videoId":"1WaV2x8GXj0","year":1963,"tags":["country"]},
    {"title":"Crazy","artist":"Patsy Cline","videoId":"DXWCaQPXE_0","year":1961,"tags":["country"]},
    {"title":"Stand By Your Man","artist":"Tammy Wynette","videoId":"wXaAsbggsN0","year":1968,"tags":["country"]},
    {"title":"Mambo No. 5","artist":"Pérez Prado","videoId":"0O_J877KJcs","year":1949,"tags":["latin"]},
    {"title":"Guantanamera","artist":"Pete Seeger","videoId":"fyRXWIVr_nE","year":1960,"tags":["folk"]},
    {"title":"Blowin' in the Wind","artist":"Bob Dylan","videoId":"MMFj8uDubsE","year":1962,"tags":["folk"]},
    {"title":"The Times They Are a-Changin'","artist":"Bob Dylan","videoId":"90WD_ats6eE","year":1963,"tags":["folk"]},
    {"title":"Like a Rolling Stone","artist":"Bob Dylan","videoId":"IwOfCgkyEj0","year":1965,"tags":["folk"]},
    {"title":"Wonderful World","artist":"Sam Cooke","videoId":"R4GLAKEjU4w","year":1960,"tags":["soul"]},
    {"title":"A Change Is Gonna Come","artist":"Sam Cooke","videoId":"wEBlaMOmKV4","year":1964,"tags":["soul"]},
    {"title":"Dock of the Bay","artist":"Otis Redding","videoId":"rTVjnBo96Ug","year":1967,"tags":["soul"]},
    {"title":"Try a Little Tenderness","artist":"Otis Redding","videoId":"pli44utBOwo","year":1966,"tags":["soul"]},
    {"title":"Sweet Soul Music","artist":"Arthur Conley","videoId":"grE0lwTsSPg","year":1967,"tags":["soul"]},
    {"title":"In My Life","artist":"The Beatles","videoId":"YBcdt6DsLQA","year":1965,"tags":["rock"]},
    {"title":"Day Tripper","artist":"The Beatles","videoId":"2IbPn5j2YKk","year":1965,"tags":["rock"]},
    {"title":"Strawberry Fields Forever","artist":"The Beatles","videoId":"8UQK-UcRezE","year":1967,"tags":["rock"]},
    {"title":"Lucy in the Sky with Diamonds","artist":"The Beatles","videoId":"l7x-0c9jl4Y","year":1967,"tags":["rock"]},
    {"title":"A Day in the Life","artist":"The Beatles","videoId":"x7Y6txDZETY","year":1967,"tags":["rock"]},
    {"title":"Hey Jude","artist":"The Beatles","videoId":"A_MjCqQoLLA","year":1968,"tags":["rock"]},
    {"title":"Revolution","artist":"The Beatles","videoId":"BGLGzRXY5Bw","year":1968,"tags":["rock"]},
    {"title":"Across the Universe","artist":"The Beatles","videoId":"90M60PzmxEE","year":1969,"tags":["rock"]},
    {"title":"Waterloo Sunset","artist":"The Kinks","videoId":"vTHv20WpE2s","year":1967,"tags":["rock"]},
    {"title":"You Really Got Me","artist":"The Kinks","videoId":"_dHK6hLNTAI","year":1964,"tags":["rock"]},
    {"title":"Sunny","artist":"Bobby Hebb","videoId":"RmNqmZZk0Ow","year":1966,"tags":["soul"]},
    {"title":"Que Sera, Sera","artist":"Doris Day","videoId":"zSKf4bpXthY","year":1956,"tags":["pop"]},
    {"title":"Fever","artist":"Peggy Lee","videoId":"JBANWpzsHts","year":1958,"tags":["pop"]},
    {"title":"Crimson and Clover","artist":"Tommy James","videoId":"XS0niyiKlcw","year":1968,"tags":["rock"]},
    {"title":"Purple Haze","artist":"Jimi Hendrix","videoId":"WGoDaYjdfSg","year":1967,"tags":["rock"]},
    {"title":"Foxy Lady","artist":"Jimi Hendrix","videoId":"d7qaHFdtVTc","year":1967,"tags":["rock"]},
    {"title":"All Along the Watchtower","artist":"Jimi Hendrix","videoId":"TLV4_xaYynY","year":1968,"tags":["rock"]},
    {"title":"Born to Be Wild","artist":"Steppenwolf","videoId":"igvP806798U","year":1968,"tags":["rock"]},
    {"title":"Susie-Q","artist":"Creedence Clearwater Revival","videoId":"7x60p7UNLnQ","year":1969,"tags":["rock"]}
  ],
  "70s": [
    {"title":"Lola","artist":"The Kinks","videoId":"6CzrYXcXweI","year":1970,"tags":["rock"]},    
    {"title":"All Right Now","artist":"Free","videoId":"lSdBtoIIYT4","year":1970,"tags":["rock"]},
    {"title":"Smoke on the Water","artist":"Deep Purple","videoId":"Q2FzZSBD5LE","year":1971,"tags":["rock"]},
    {"title":"El Condor Pasa","artist":"Simon & Garfunkel","videoId":"ZrZn8Ln4ryg","year":1970,"tags":["folk"]},
    {"title":"Jolene","artist":"Dolly Parton","videoId":"Ixrje2rXLMA","year":1973,"tags":["country"]},
    {"title":"Piano Man","artist":"Billy Joel","videoId":"rwzccnhN-iw","year":1973,"tags":["pop"]},
    {"title":"So Lonely","artist":"The Police","videoId":"xTtaegHAllQ","year":1978,"tags":["rock"]},
    {"title":"Barracuda","artist":"Heart","videoId":"PeMvMNpvB5M","year":1977,"tags":["rock"]},
    {"title":"Cocaine","artist":"Eric Clapton","videoId":"tyw8Hg3jpoA","year":1977,"tags":["rock"]},
    {"title":"Wonderful Tonight","artist":"Eric Clapton","videoId":"UprwkbzUX6g","year":1977,"tags":["rock"]},
    {"title":"Lay Down Sally","artist":"Eric Clapton","videoId":"9BYyPok2O5k","year":1977,"tags":["rock"]},
    {"title":"Bohemian Rhapsody","artist":"Queen","videoId":"fJ9rUzIMcZQ","year":1975,"tags":["rock"]},
    {"title":"Stayin' Alive","artist":"Bee Gees","videoId":"I_izvAbhExY","year":1977,"tags":["disco"]},
    {"title":"Hotel California","artist":"Eagles","videoId":"09839DpTctU","year":1976,"tags":["rock"]},
    {"title":"Imagine","artist":"John Lennon","videoId":"YkgkThdzX-8","year":1971,"tags":["pop"]},
    {"title":"Superstition","artist":"Stevie Wonder","videoId":"0CFuCYNx-1g","year":1972,"tags":["funk"]},
    {"title":"Dancing Queen","artist":"ABBA","videoId":"xFrGuyw1V8s","year":1976,"tags":["pop"]},
    {"title":"Le Freak","artist":"Chic","videoId":"h1qQ1SKNlgY","year":1978,"tags":["disco"]},
    {"title":"September","artist":"Earth, Wind & Fire","videoId":"Gs069dndIYk","year":1978,"tags":["funk"]},
    {"title":"Go Your Own Way","artist":"Fleetwood Mac","videoId":"6ul-cZyuYq4","year":1977,"tags":["rock"]},
    {"title":"Roxanne","artist":"The Police","videoId":"3T1c7GkzRQQ","year":1978,"tags":["rock"]},
    {"title":"We Will Rock You","artist":"Queen","videoId":"-tJYN-eG1zk","year":1977,"tags":["rock"]},
    {"title":"Blame It on the Boogie","artist":"Jacksons","videoId":"nqxVMLVe62U","year":1978,"tags":["funk"]},
    {"title":"I Will Survive","artist":"Gloria Gaynor","videoId":"6dYWe1c3OyU","year":1978,"tags":["disco"]},
    {"title":"Dreams","artist":"Fleetwood Mac","videoId":"5oWyMakvQew","year":1977,"tags":["rock"]},
    {"title":"Let It Be","artist":"The Beatles","videoId":"QDYfEBY9NM4","year":1970,"tags":["rock"]},
    {"title":"American Pie","artist":"Don McLean","videoId":"PRpiBpDy7MQ","year":1971,"tags":["folk"]},
    {"title":"Car Wash","artist":"Rose Royce","videoId":"PkxaunLybuM","year":1976,"tags":["funk"]},
    {"title":"Play That Funky Music","artist":"Wild Cherry","videoId":"MDZsNksbw2Q","year":1976,"tags":["funk"]},
    {"title":"Don't Stop Me Now","artist":"Queen","videoId":"HgzGwKwLmgM","year":1979,"tags":["rock"]},
    {"title":"Heart of Glass","artist":"Blondie","videoId":"WGU_4-5RaxU","year":1979,"tags":["pop"]},
    {"title":"Night Fever","artist":"Bee Gees","videoId":"SkypZuY6ZvA","year":1977,"tags":["disco"]},
    {"title":"Disco Inferno","artist":"Trammps","videoId":"zcua9XzKVas","year":1976,"tags":["disco"]},
    {"title":"Tragedy","artist":"Bee Gees","videoId":"I248-SyRDnU","year":1979,"tags":["disco"]},
    {"title":"Boogie Wonderland","artist":"Earth, Wind & Fire","videoId":"god7hAPv8f0","year":1978,"tags":["funk"]},
    {"title":"Get Down Tonight","artist":"KC & The Sunshine Band","videoId":"CjnuUDoyn54","year":1975,"tags":["disco"]},
    {"title":"That's the Way (I Like It)","artist":"KC & The Sunshine Band","videoId":"gFrd3WiOcPc","year":1975,"tags":["disco"]},
    {"title":"Shake Your Groove Thing","artist":"Peaches & Herb","videoId":"e-LeujZNV08","year":1978,"tags":["disco"]},
    {"title":"Good Times","artist":"Chic","videoId":"Q5C9oeKxJzo","year":1979,"tags":["disco"]},
    {"title":"Uptown Top Ranking","artist":"Althia & Donna","videoId":"VE-A5JULvRM","year":1977,"tags":["reggae"]},
    {"title":"No Woman No Cry","artist":"Bob Marley","videoId":"IT8XvzIfi4U","year":1974,"tags":["reggae"]},
    {"title":"Get Up Stand Up","artist":"Bob Marley","videoId":"RhJ0q7X3DLM","year":1973,"tags":["reggae"]},
    {"title":"Waiting in Vain","artist":"Bob Marley","videoId":"IWxbhC44p2w","year":1977,"tags":["reggae"]},
    {"title":"Exodus","artist":"Bob Marley","videoId":"OSOqWgqwynQ","year":1977,"tags":["reggae"]},
    {"title":"One Love","artist":"Bob Marley","videoId":"IN0KkGeEURw","year":1977,"tags":["reggae"]},
    {"title":"Kung Fu Fighting","artist":"Carl Douglas","videoId":"Bt4D8oA3mxU","year":1974,"tags":["pop"]},
    {"title":"Spirit in the Sky","artist":"Norman Greenbaum","videoId":"YqYN-1vMM9k","year":1969,"tags":["rock"]},
    {"title":"Ring My Bell","artist":"Anita Ward","videoId":"AvEcIeWhjyU","year":1979,"tags":["disco"]},
    {"title":"Dancing in Moonlight","artist":"King Harvest","videoId":"g5JqPxmYhlo","year":1972,"tags":["pop"]},
    {"title":"Afternoon Delight","artist":"Starland Vocal Band","videoId":"7JtCA0esyOU","year":1976,"tags":["pop"]},
    {"title":"Muskrat Love","artist":"Captain & Tennille","videoId":"N2BuP-NcJ5Q","year":1976,"tags":["pop"]},
    {"title":"Love Will Keep Us Together","artist":"Captain & Tennille","videoId":"ivJq9lmCWkc","year":1975,"tags":["pop"]},
    {"title":"Torn Between Two Lovers","artist":"Mary MacGregor","videoId":"0URFfZx9otI","year":1976,"tags":["pop"]},
    {"title":"You Light Up My Life","artist":"Debby Boone","videoId":"UAH-pbsN1Xw","year":1977,"tags":["pop"]},
    {"title":"Mandy","artist":"Barry Manilow","videoId":"4oh5fEIpx-E","year":1974,"tags":["pop"]},
    {"title":"Copacabana","artist":"Barry Manilow","videoId":"NKR2n-G-wdM","year":1978,"tags":["pop"]},
    {"title":"Feelings","artist":"Perry Como","videoId":"P_T6yN83ML4","year":1978,"tags":["pop"]},
    {"title":"How Deep Is Your Love","artist":"Bee Gees","videoId":"XpqqjU7u5Yc","year":1977,"tags":["disco"]},
    {"title":"Disco Lady","artist":"Johnnie Taylor","videoId":"U4aiBO8RPzk","year":1975,"tags":["disco"]},
    {"title":"Mamma Mia","artist":"ABBA","videoId":"unfzfe8f9NI","year":1975,"tags":["pop"]},
    {"title":"Waterloo","artist":"ABBA","videoId":"Sj_9CiNkkn4","year":1974,"tags":["pop"]},
    {"title":"Fernando","artist":"ABBA","videoId":"dQsjAbZDx-4","year":1976,"tags":["pop"]},
    {"title":"Gimme Gimme Gimme","artist":"ABBA","videoId":"XEjLoHdbVeE","year":1979,"tags":["pop"]},
    {"title":"SOS","artist":"ABBA","videoId":"cvChjHcABPA","year":1975,"tags":["pop"]},
    {"title":"Take a Chance on Me","artist":"ABBA","videoId":"-crgQGdpZR0","year":1977,"tags":["pop"]},
    {"title":"Knock on Wood","artist":"Amii Stewart","videoId":"XKuJUxGntRI","year":1978,"tags":["disco"]},
    {"title":"I'm Every Woman","artist":"Chaka Khan","videoId":"DVDCNmdi7QI","year":1978,"tags":["funk"]},
    {"title":"Love's Theme","artist":"Love Unlimited Orchestra","videoId":"n7YQGHHGoXg","year":1973,"tags":["funk"]},
    {"title":"Rock with You","artist":"Michael Jackson","videoId":"5X-Mrc2l1d0","year":1979,"tags":["disco"]},
    {"title":"Off the Wall","artist":"Michael Jackson","videoId":"MYPI0HZGVR4","year":1979,"tags":["disco"]},
    {"title":"Don't Stop Till You Get Enough","artist":"Michael Jackson","videoId":"yURRmWtbTbo","year":1979,"tags":["disco"]},
    {"title":"但願人長久","artist":"Teresa Teng","videoId":"wA0H7Zvb0u4","year":1978,"tags":["mandopop"]},
    {"title":"甜蜜蜜","artist":"Teresa Teng","videoId":"5eF8oOWtsk4","year":1979,"tags":["mandopop"]},
    {"title":"漫步人生路","artist":"Teresa Teng","videoId":"XPB6ZaNUzn4","year":1978,"tags":["mandopop"]},
    {"title":"浪子心聲","artist":"Sam Hui","videoId":"qh49HEuVhyA","year":1976,"tags":["cantopop"]},
    {"title":"半斤八兩","artist":"Sam Hui","videoId":"zgCxI6heNMQ","year":1976,"tags":["cantopop"]},
    {"title":"鐵塔凌雲","artist":"Sam Hui","videoId":"iLsqE9BiwZg","year":1972,"tags":["cantopop"]},
    {"title":"賣身契","artist":"Sam Hui","videoId":"X0sevSWDOE8","year":1972,"tags":["cantopop"]},
    {"title":"搵嘢做","artist":"Sam Hui","videoId":"LczmuKdE0qs","year":1978,"tags":["cantopop"]},
    {"title":"學生哥","artist":"Sam Hui","videoId":"zytOXQxTOlc","year":1978,"tags":["cantopop"]},
    {"title":"有酒今朝醉","artist":"Sam Hui","videoId":"6tC6UO65xTc","year":1978,"tags":["cantopop"]},
    {"title":"又見炊煙","artist":"Teresa Teng","videoId":"hDCBDKokadE","year":1978,"tags":["mandopop"]},
    {"title":"月亮代表我的心","artist":"Teresa Teng","videoId":"IgvDMB5fR-8","year":1977,"tags":["mandopop"]},
    {"title":"Yesterday Once More","artist":"Carpenters","videoId":"YTaWayUE5XA","year":1973,"tags":["pop"]},
    {"title":"We've Only Just Begun","artist":"Carpenters","videoId":"9hJCr9cq5co","year":1970,"tags":["pop"]},
    {"title":"Close to You","artist":"Carpenters","videoId":"iFx-5PGLgb4","year":1970,"tags":["pop"]},
    {"title":"Superstition (Live)","artist":"Stevie Wonder","videoId":"97hwNY3ni10","year":1972,"tags":["funk"]},
    {"title":"As","artist":"Stevie Wonder","videoId":"GYQfWJNWe3I","year":1976,"tags":["soul"]},
    {"title":"You Are the Sunshine of My Life","artist":"Stevie Wonder","videoId":"yYj1DMHwFy4","year":1972,"tags":["soul"]},
    {"title":"Isn't She Lovely","artist":"Stevie Wonder","videoId":"uPBvq7yewIk","year":1974,"tags":["soul"]},
    {"title":"Boys Don't Cry","artist":"The Cure","videoId":"MEqjpgwPjVM","year":1979,"tags":["rock"]},
    {"title":"Hole in the Roof","artist":"Thin Lizzy","videoId":"Q3-TwrVDhD8","year":1977,"tags":["rock"]}
  ],
  "80s": [
    {"title":"光輝歲月","artist":"Beyond","videoId":"PrGsAMbgUh4","year":1989,"tags":["cantopop"]},
    {"title":"千千闋歌","artist":"Priscilla Chan","videoId":"1Ssfvf_I4AM","year":1989,"tags":["cantopop"]},
    {"title":"The Lady in My Life","artist":"Michael Jackson","videoId":"hbjIhgk_X18","year":1982,"tags":["pop"]},
    {"title":"Human Nature","artist":"Michael Jackson","videoId":"YNzuiRuQNYY","year":1983,"tags":["pop"]},
    {"title":"The Girl Is Mine","artist":"Michael Jackson","videoId":"8GB9BULxZ8c","year":1982,"tags":["pop"]},
    {"title":"P.Y.T. (Pretty Young Thing)","artist":"Michael Jackson","videoId":"1ZZQuj6htF4","year":1982,"tags":["pop"]},
    {"title":"Dirty Diana","artist":"Michael Jackson","videoId":"yUi_S6YWjZw","year":1987,"tags":["pop"]},
    {"title":"Pressure","artist":"Billy Joel","videoId":"y8JL47Kcb6M","year":1982,"tags":["pop"]},
    {"title":"You're the Only Woman","artist":"Ambrosia","videoId":"CsRW5uZryQc","year":1980,"tags":["pop"]},
    {"title":"Blue Monday","artist":"New Order","videoId":"TsgLhkjY4q0","year":1983,"tags":["electronic"]},
    {"title":"Just Like Heaven","artist":"The Cure","videoId":"1ASpBpT8bRQ","year":1987,"tags":["rock"]},
    {"title":"King of Pain","artist":"The Police","videoId":"dWd371wAA3s","year":1983,"tags":["rock"]},
    {"title":"Wrapped Around Your Finger","artist":"The Police","videoId":"svWINSRhQU0","year":1983,"tags":["rock"]},
    {"title":"Love Shack","artist":"The B-52's","videoId":"9SOryJvTAGs","year":1989,"tags":["pop"]},
    {"title":"Mickey","artist":"Toni Basil","videoId":"qXVlpUg2WXg","year":1981,"tags":["pop"]},
    {"title":"99 Luftballons","artist":"Nena","videoId":"Fpu5a0Bl8eY","year":1983,"tags":["rock"]},
    {"title":"Obsession","artist":"Animotion","videoId":"hIs5StN8J-0","year":1984,"tags":["pop"]},
    {"title":"I Just Called to Say I Love You","artist":"Stevie Wonder","videoId":"58RgLQ_0Ars","year":1984,"tags":["pop"]},
    {"title":"Endless Love","artist":"Diana Ross & Lionel Richie","videoId":"ubrfaD9DIus","year":1981,"tags":["pop"]},
    {"title":"Against All Odds","artist":"Phil Collins","videoId":"wuvtoyVi7vY","year":1984,"tags":["pop"]},
    {"title":"In Your Eyes","artist":"Peter Gabriel","videoId":"kU8OJAOMbPg","year":1986,"tags":["pop"]},
    {"title":"Don't Give Up (ft. Kate Bush)","artist":"Peter Gabriel & Kate Bush","videoId":"VjEq-r2agqc","year":1986,"tags":["pop"]},
    {"title":"Sledgehammer","artist":"Peter Gabriel","videoId":"OJWJE0x7T4Q","year":1986,"tags":["pop"]},
    {"title":"Uptown Girl","artist":"Billy Joel","videoId":"hCuMWrfXG4E","year":1983,"tags":["pop"]},
    {"title":"Don't You (Forget About Me)","artist":"Simple Minds","videoId":"CdqoNKCCt7A","year":1985,"tags":["rock"]},
    {"title":"Glory Days","artist":"Bruce Springsteen","videoId":"6vQpW9XRiyM","year":1984,"tags":["rock"]},
    {"title":"Born in the USA","artist":"Bruce Springsteen","videoId":"EPhWR4d3FJQ","year":1984,"tags":["rock"]},
    {"title":"Dancing in the Sheets","artist":"Shalamar","videoId":"fZmHu1t_5X0","year":1984,"tags":["funk"]},
    {"title":"Footloose","artist":"Kenny Loggins","videoId":"ltrMfT4Qz5Y","year":1984,"tags":["pop"]},
    {"title":"Let's Dance","artist":"David Bowie","videoId":"VbD_kBJc_gI","year":1983,"tags":["rock"]},
    {"title":"Modern Love","artist":"David Bowie","videoId":"HivQqTtiHVw","year":1983,"tags":["rock"]},
    {"title":"China Girl","artist":"David Bowie","videoId":"_YC3sTbAPcU","year":1983,"tags":["rock"]},
    {"title":"Rebel Yell","artist":"Billy Idol","videoId":"VdphvuyaV_I","year":1983,"tags":["rock"]},
    {"title":"Cum on Feel the Noize","artist":"Quiet Riot","videoId":"ZxgMGk9JPVA","year":1983,"tags":["rock"]},
    {"title":"Total Eclipse of the Heart","artist":"Bonnie Tyler","videoId":"lcOxhH8N3Bo","year":1983,"tags":["rock"]},
    {"title":"Like a Virgin","artist":"Madonna","videoId":"sVh90UIBm44","year":1984,"tags":["pop"]},
    {"title":"Redemption Song","artist":"Bob Marley","videoId":"yv5xonFSC4c","year":1980,"tags":["reggae"]},
    {"title":"Material Girl","artist":"Madonna","videoId":"6p-lDYPR2P8","year":1984,"tags":["pop"]},
    {"title":"Into the Groove","artist":"Madonna","videoId":"52i3lcpK5M","year":1985,"tags":["pop"]},
    {"title":"Vogue","artist":"Madonna","videoId":"GuJQSAiODqI","year":1990,"tags":["pop"]},
    {"title":"Express Yourself","artist":"Madonna","videoId":"GsVcUzP_O_8","year":1989,"tags":["pop"]},
    {"title":"Waltz Darling","artist":"Malcolm McLaren","videoId":"vkGiirlQ11I","year":1989,"tags":["pop"]},
    {"title":"It's My Life","artist":"Talk Talk","videoId":"cFH5JgyZK1I","year":1984,"tags":["pop"]},
    {"title":"Down Under","artist":"Men at Work","videoId":"XfR9iY5y94s","year":1981,"tags":["pop"]},
    {"title":"Come On Eileen","artist":"Dexys Midnight Runners","videoId":"6BODDyZRF6A","year":1982,"tags":["pop"]},
    {"title":"Eye of the Tiger","artist":"Survivor","videoId":"btPJPFnesV4","year":1982,"tags":["rock"]},
    {"title":"Livin' on a Prayer","artist":"Bon Jovi","videoId":"lDK9QqIzhwk","year":1986,"tags":["rock"]},
    {"title":"Time After Time","artist":"Cyndi Lauper","videoId":"VdQY7BusJNU","year":1984,"tags":["pop"]},
    {"title":"Take My Breath Away","artist":"Berlin","videoId":"Bx51eegLTY8","year":1986,"tags":["pop"]},
    {"title":"Hungry Like the Wolf","artist":"oJL-lCzEXgI","year":1982,"tags":["pop"]},
    {"title":"Karma Chameleon","artist":"Culture Club","videoId":"JmcA9LIIXWw","year":1983,"tags":["pop"]},
    {"title":"Flashdance... What a Feeling","artist":"Irene Cara","videoId":"ILWSp0m9G2U","year":1983,"tags":["pop"]},
    {"title":"Nothing's Gonna Stop Us Now","artist":"Starship","videoId":"3wxyN3z9PL4","year":1987,"tags":["pop"]},
    {"title":"Every Breath You Take","artist":"The Police","videoId":"OMOGaugKpzs","year":1983,"tags":["rock"]},
    {"title":"Wake Me Up Before You Go-Go","artist":"Wham!","videoId":"pIgZ7gMze7A","year":1984,"tags":["pop"]},
    {"title":"Jump","artist":"Van Halen","videoId":"SwYN7mTi6HM","year":1984,"tags":["rock"]},
    {"title":"The Winner Takes It All","artist":"ABBA","videoId":"92cwKCU8Z5c","year":1980,"tags":["pop"]},
    {"title":"Could You Be Loved","artist":"Bob Marley","videoId":"1ti2YCFgCoI","year":1980,"tags":["reggae"]},
    {"title":"Three Little Birds","artist":"Bob Marley","videoId":"HNBCVM4KbUM","year":1980,"tags":["reggae"]},
    {"title":"Buffalo Soldier","artist":"Bob Marley","videoId":"uMUQMSXLlHM","year":1983,"tags":["reggae"]},
    {"title":"I Just Called to Say I Love You","artist":"Stevie Wonder","videoId":"1bGOgY1CmiU","year":1984,"tags":["pop"]},
    {"title":"Edge of Seventeen","artist":"Stevie Nicks","videoId":"UmPgMc3R8zg","year":1981,"tags":["rock"]},
    {"title":"Leather and Lace","artist":"Stevie Nicks","videoId":"BGLz_xs3Ots","year":1981,"tags":["rock"]},
    {"title":"Pride and Joy","artist":"Stevie Ray Vaughan","videoId":"kfjXp4KTTY8","year":1985,"tags":["blues"]},
    {"title":"Lenny","artist":"Stevie Ray Vaughan","videoId":"i5sqJNFFwqc","year":1985,"tags":["blues"]},
    {"title":"Texas Flood","artist":"Stevie Ray Vaughan","videoId":"KC5H9P4F5Uk","year":1983,"tags":["blues"]},
    {"title":"Riviera Paradise","artist":"Stevie Ray Vaughan","videoId":"3c_8VUL5jks","year":1987,"tags":["blues"]},
    {"title":"Billie Jean","artist":"Michael Jackson","videoId":"Zi_XLOBDo_Y","year":1983,"tags":["pop"]},
    {"title":"Take On Me","artist":"a-ha","videoId":"djV11Xbc914","year":1985,"tags":["pop"]},
    {"title":"Sweet Child O' Mine","artist":"Guns N' Roses","videoId":"1w7OgIMMRc4","year":1987,"tags":["rock"]},
    {"title":"Welcome to the Jungle","artist":"Guns N' Roses","videoId":"o1tj2zJ2Wvg","year":1988,"tags":["rock"]},
    {"title":"Like a Prayer","artist":"Madonna","videoId":"79fzeNUqQbQ","year":1989,"tags":["pop"]},
    {"title":"Africa","artist":"Toto","videoId":"FTQbiNvZqaY","year":1982,"tags":["rock"]},
    {"title":"Beat It","artist":"Michael Jackson","videoId":"oRdxUFDoQe0","year":1983,"tags":["pop"]},
    {"title":"Thriller","artist":"Michael Jackson","videoId":"sOnqjkJTMaA","year":1983,"tags":["pop"]},
    {"title":"Girls Just Want to Have Fun","artist":"Cyndi Lauper","videoId":"PIb6AZdTr-A","year":1983,"tags":["pop"]},
    {"title":"Careless Whisper","artist":"George Michael","videoId":"izGwDsrQ1eQ","year":1984,"tags":["pop"]},
    {"title":"Never Gonna Give You Up","artist":"Rick Astley","videoId":"dQw4w9WgXcQ","year":1987,"tags":["pop"]},
    {"title":"在水一方","artist":"Teresa Teng","videoId":"9d2HY6xPCYw","year":1980,"tags":["mandopop"]},
    {"title":"真的愛你","artist":"Beyond","videoId":"n8aK_IUna_Y","year":1989,"tags":["cantopop"]},
    {"title":"大地","artist":"Beyond","videoId":"9vtFEeTth8c","year":1988,"tags":["cantopop"]},
    {"title":"夕陽之歌","artist":"Anita Mui","videoId":"XnNIPXT9YvE","year":1989,"tags":["cantopop"]}
  ],
  "90s": [
    {"title":"Disco 2000","artist":"Pulp","videoId":"iYfhhHpqUow","year":1995,"tags":["britpop"]},
    {"title":"Common People","artist":"Pulp","videoId":"yuTMWgOduFM","year":1995,"tags":["britpop"]},
    {"title":"Bitter Sweet Symphony","artist":"The Verve","videoId":"1lyu1KKwC74","year":1997,"tags":["britpop"]},
    {"title":"Wonderwall","artist":"Oasis","videoId":"bx1Bh8ZvH84","year":1995,"tags":["britpop"]},
    {"title":"November Rain","artist":"Guns N' Roses","videoId":"8SbUC-UaAxE","year":1991,"tags":["rock"]},
    {"title":"Knocking on Heaven's Door","artist":"Guns N' Roses","videoId":"k04tX2fvh0o","year":1991,"tags":["rock"]},
    {"title":"Civil War","artist":"Guns N' Roses","videoId":"ucDiz3GYrg","year":1990,"tags":["rock"]},
    {"title":"More Than Words","artist":"Extreme","videoId":"UrIiLvg58SY","year":1990,"tags":["rock"]},
    {"title":"Hallelujah","artist":"Jeff Buckley","videoId":"y8AWFf7EAc4","year":1994,"tags":["rock"]},
    {"title":"My Heart Will Go On","artist":"Celine Dion","videoId":"9bFHsd3o1w0","year":1997,"tags":["pop"]},
    {"title":"Losing My Religion","artist":"R.E.M.","videoId":"xwtdhWltSIg","year":1991,"tags":["rock"]},
    {"title":"Baby Come On Over","artist":"Samantha Mumba","videoId":"1lu5dj7unxY","year":1999,"tags":["pop"]},
    {"title":"Don't Look Back in Anger","artist":"Oasis","videoId":"YZG7z4FOn0g","year":1995,"tags":["britpop"]},
    {"title":"Supersonic","artist":"Oasis","videoId":"FOTsS2mplA0","year":1994,"tags":["britpop"]},
    {"title":"Song 2","artist":"Blur","videoId":"4TzVWs-hU3M","year":1997,"tags":["britpop"]},
    {"title":"Parklife","artist":"Blur","videoId":"YSuHrTfcikU","year":1994,"tags":["britpop"]},
    {"title":"There's No Other Way","artist":"Blur","videoId":"LJzCYSdrHMI","year":1991,"tags":["britpop"]},
    {"title":"Champagne Supernova","artist":"Oasis","videoId":"tI-5uv4wryI","year":1995,"tags":["britpop"]},
    {"title":"Girls & Boys","artist":"Blur","videoId":"WDswiT87oo8","year":1994,"tags":["britpop"]}
    {"title":"Losing My Religion","artist":"R.E.M.","videoId":"xwtdhWltSIg","year":1991,"tags":["rock"]},
    {"title":"Black or White","artist":"Michael Jackson","videoId":"F2AitTPI5U0","year":1991,"tags":["pop"]},
    {"title":"Creep","artist":"Radiohead","videoId":"XFkzRNyygfk","year":1992,"tags":["rock"]},
    {"title":"I Want It That Way","artist":"Backstreet Boys","videoId":"4fndeDfaWCg","year":1999,"tags":["pop"]},
    {"title":"Genie in a Bottle","artist":"Christina Aguilera","videoId":"kIDWgqDBNXA","year":1999,"tags":["pop"]},
    {"title":"Gangsta's Paradise","artist":"Coolio","videoId":"SQCSxqScSVQ","year":1995,"tags":["hiphop"]},
    {"title":"Waterfalls","artist":"TLC","videoId":"8WEtxJ4-sh4","year":1995,"tags":["rnb"]},
    {"title":"Say My Name","artist":"Destiny's Child","videoId":"sQgd6MccwZc","year":1999,"tags":["rnb"]},
    {"title":"Enter Sandman","artist":"Metallica","videoId":"CD-E-LDc384","year":1991,"tags":["rock"]},
    {"title":"Macarena","artist":"Los Del Rio","videoId":"zWaymcVmJ-A","year":1993,"tags":["latin"]},
    {"title":"Livin' la Vida Loca","artist":"Ricky Martin","videoId":"p47fEXGabaY","year":1999,"tags":["latin"]},
    {"title":"Torn","artist":"Natalie Imbruglia","videoId":"Alwek_UJofA","year":1997,"tags":["pop"]},
    {"title":"Iris","artist":"Goo Goo Dolls","videoId":"NdYWuo9OFAw","year":1998,"tags":["rock"]},
    {"title":"Vogue","artist":"Madonna","videoId":"GuJQSAiODqI","year":1990,"tags":["pop"]},     
    {"title":"Wonderwall","artist":"Oasis","videoId":"bx1Bh8ZvH84","year":1995,"tags":["rock"]},
    {"title":"Smells Like Teen Spirit","artist":"Nirvana","videoId":"hTWKbfoikeg","year":1991,"tags":["rock"]},
    {"title":"...Baby One More Time","artist":"Britney Spears","videoId":"C-u5WLJ9Yk4","year":1998,"tags":["pop"]},
    {"title":"No Scrubs","artist":"TLC","videoId":"FrLequ6dUdM","year":1999,"tags":["rnb"]},
    {"title":"Tears in Heaven","artist":"Eric Clapton","videoId":"tUU1GLMdnkM","year":1992,"tags":["rock"]},
    {"title":"Layla (Unplugged)","artist":"Eric Clapton","videoId":"kseSoguuiCs","year":1992,"tags":["rock"]},
    {"title":"Change the World","artist":"Eric Clapton","videoId":"nXB4xBnP22o","year":1996,"tags":["rock"]},
    {"title":"More Than Words","artist":"Extreme","videoId":"UrIiLvg58SY","year":1990,"tags":["rock"]},
    {"title":"The Sky Is Crying","artist":"Stevie Ray Vaughan","videoId":"6s9M-52fRGU","year":1991,"tags":["blues"]},
    {"title":"Friday I'm in Love","artist":"The Cure","videoId":"mGgMZpGYiy8","year":1992,"tags":["rock"]},
    {"title":"農民","artist":"Beyond","videoId":"YMC3wrwdMqI","year":1992,"tags":["mandopop"]}, 
    {"title":"不再猶豫","artist":"Beyond","videoId":"fKKgY7BXxJE","year":1991,"tags":["cantopop"]},
    {"title":"海闊天空","artist":"Beyond","videoId":"V4GUy2EHMMs","year":1993,"tags":["cantopop"]},
    {"title":"我是不是該安靜地走開","artist":"Aaron Kwok","videoId":"ZPp_rvDB-pY","year":1991,"tags":["mandopop"]},
    {"title":"真的愛你","artist":"Beyond","videoId":"n8aK_IUna_Y","year":1990,"tags":["cantopop"]},
    {"title":"我想和你去吹風","artist":"Jacky Cheung","videoId":"sTPnrknKlTs","year":1997,"tags":["mandopop"]},
    {"title":"一千個傷心的理由","artist":"Jacky Cheung","videoId":"Yl9sIjmaZP8","year":1995,"tags":["mandopop"]},
    {"title":"祇想一生跟你走","artist":"Jacky Cheung","videoId":"X9ZyFxDwR0s","year":1993,"tags":["cantopop"]},
    {"title":"心如刀割","artist":"Jacky Cheung","videoId":"CA5CwZ4Nmnk","year":1999,"tags":["mandopop"]},
    {"title":"一路上有你","artist":"Jacky Cheung","videoId":"IgvK6sqGFtI","year":1999,"tags":["mandopop"]},
    {"title":"她來聽我的演唱會","artist":"Jacky Cheung","videoId":"QJjSLe8Kt4I","year":1993,"tags":["mandopop"]},
    {"title":"孤身在外","artist":"Jacky Cheung & Francesca Kao","videoId":"_SODktUwNYo","year":1998,"tags":["mandopop"]},
    {"title":"紅茶館","artist":"Priscilla Chan","videoId":"jOADn2-U8ro","year":1992,"tags":["cantopop"]},
    {"title":"似是故人來","artist":"Anita Mui","videoId":"weBaxurJxFc","year":1991,"tags":["cantopop"]},
    {"title":"親密愛人","artist":"Anita Mui","videoId":"jXJqP9rOQ38","year":1991,"tags":["mandopop"]},
    {"title":"光輝歲月","artist":"Beyond","videoId":"E62MSMgkqG4","year":1990,"tags":["cantopop"]}

  ],
  "00s": [
    {"title":"Hey Ya!","artist":"Outkast","videoId":"PWgvGjAhvIw","year":2003,"tags":["hiphop"]},
    {"title":"In the End","artist":"Linkin Park","videoId":"eVTXPUF4Oz4","year":2000,"tags":["rock"]},
    {"title":"Umbrella","artist":"Rihanna","videoId":"CvBfHwUxHIk","year":2007,"tags":["pop"]},
    {"title":"Hips Don't Lie","artist":"Shakira","videoId":"DUT5rEU6pqM","year":2006,"tags":["latin"]},
    {"title":"Yeah!","artist":"Usher","videoId":"GxBSyx85Kp8","year":2004,"tags":["rnb"]},
    {"title":"Toxic","artist":"Britney Spears","videoId":"LOZuxwVk7TU","year":2004,"tags":["pop"]},
    {"title":"Boulevard of Broken Dreams","artist":"Green Day","videoId":"Soa3gO7tL-c","year":2004,"tags":["rock"]},
    {"title":"Poker Face","artist":"Lady Gaga","videoId":"bESGLojNYSo","year":2008,"tags":["pop"]},
    {"title":"Bad Romance","artist":"Lady Gaga","videoId":"qrO4YZeyl0I","year":2009,"tags":["pop"]},
    {"title":"Mr. Brightside","artist":"The Killers","videoId":"gGdGFtwCNBE","year":2003,"tags":["rock"]},
    {"title":"Gold Digger","artist":"Kanye West","videoId":"6vwNcNOTVzY","year":2005,"tags":["hiphop"]},
    {"title":"Crazy","artist":"Gnarls Barkley","videoId":"N4jf6rtyuw","year":2006,"tags":["soul"]},
    {"title":"Temperature","artist":"Sean Paul","videoId":"dW2MmuA1nI4","year":2005,"tags":["dancehall"]},
    {"title":"Beautiful Girls","artist":"Sean Kingston","videoId":"MrTz5xjmso4","year":2007,"tags":["pop"]},
    {"title":"American Boy","artist":"Estelle","videoId":"Ic5vxw3eijY","year":2008,"tags":["rnb"]},
    {"title":"Complicated","artist":"Avril Lavigne","videoId":"5NPBIwQyPWE","year":2002,"tags":["pop"]},
    {"title":"Gee","artist":"Girls' Generation","videoId":"U7mPqycQ0tQ","year":2009,"tags":["kpop"]},
    {"title":"Sorry Sorry","artist":"Super Junior","videoId":"x6QA3m58DQw","year":2009,"tags":["kpop"]},
    {"title":"Numb","artist":"Linkin Park","videoId":"kXYiU_JCYtU","year":2003,"tags":["rock"]},
    {"title":"Dilemma","artist":"Nelly","videoId":"8WYHDfJDPDc","year":2002,"tags":["hiphop"]},
    {"title":"Beautiful","artist":"Christina Aguilera","videoId":"eAfyFTzZDMM","year":2002,"tags":["pop"]},
    {"title":"Without Me","artist":"Eminem","videoId":"YVkUvmDQ3HY","year":2002,"tags":["hiphop"]},
    {"title":"Crazy in Love","artist":"Beyoncé","videoId":"ViwtNLUqkMY","year":2003,"tags":["pop"]},
    {"title":"Single Ladies","artist":"Beyoncé","videoId":"4m1EFMoRFvY","year":2008,"tags":["pop"]},
    {"title":"Halo","artist":"Beyoncé","videoId":"bnVUHWCynig","year":2008,"tags":["pop"]},
    {"title":"If U Seek Amy","artist":"Britney Spears","videoId":"0aEnnH6t8Ts","year":2009,"tags":["pop"]},
    {"title":"Oops!... I Did It Again","artist":"Britney Spears","videoId":"CduA0TULnow","year":2000,"tags":["pop"]},
    {"title":"Womanizer","artist":"Britney Spears","videoId":"rMqayQ-U74s","year":2008,"tags":["pop"]},
    {"title":"Try Again","artist":"Aaliyah","videoId":"qTA0RuZoIxM","year":2000,"tags":["rnb"]},
    {"title":"Lose Yourself","artist":"Eminem","videoId":"_Yhyp-_hX2s","year":2002,"tags":["hiphop"]},
    {"title":"In Da Club","artist":"50 Cent","videoId":"5qm8PH4xAss","year":2003,"tags":["hiphop"]},
    {"title":"Hollaback Girl","artist":"Gwen Stefani","videoId":"Kgjkth6BRRY","year":2005,"tags":["pop"]},
    {"title":"Hot in Herre","artist":"Nelly","videoId":"GeZZr_p6vB8","year":2002,"tags":["hiphop"]},
    {"title":"SexyBack","artist":"Justin Timberlake","videoId":"3gOHvDP_vCs","year":2006,"tags":["pop"]},
    {"title":"Bleeding Love","artist":"Leona Lewis","videoId":"7_weSk0BonM","year":2007,"tags":["pop"]},
    {"title":"Viva la Vida","artist":"Coldplay","videoId":"dvgZkm1xWPE","year":2008,"tags":["rock"]},
    {"title":"Chasing Cars","artist":"Snow Patrol","videoId":"GemKqzILV4w","year":2004,"tags":["rock"]},
    {"title":"Use Somebody","artist":"Kings of Leon","videoId":"gnhXHvRoUd0","year":2008,"tags":["rock"]},
    {"title":"Sex on Fire","artist":"Kings of Leon","videoId":"RF0HhrwIwp0","year":2010,"tags":["rock"]},
    {"title":"Take Me Out","artist":"Franz Ferdinand","videoId":"Ijk4j-r7qPA","year":2004,"tags":["rock"]},
    {"title":"Seven Nation Army","artist":"The White Stripes","videoId":"0J2QdDbelmY","year":2003,"tags":["rock"]},
    {"title":"American Idiot","artist":"Green Day","videoId":"Ee_uujKuJMI","year":2004,"tags":["rock"]},
    {"title":"Wake Me Up When September Ends","artist":"Green Day","videoId":"NU9JoFKlaZ0","year":2004,"tags":["rock"]},
    {"title":"Bring Me to Life","artist":"Evanescence","videoId":"xUBYzpCNQ1I","year":2003,"tags":["rock"]},
    {"title":"My Immortal","artist":"Evanescence","videoId":"5anLPw0Efmo","year":2003,"tags":["rock"]},
    {"title":"Last Nite","artist":"The Strokes","videoId":"TOypSnKFHrE","year":2001,"tags":["rock"]},
    {"title":"Reptilia","artist":"The Strokes","videoId":"b8-tXG8KrWs","year":2003,"tags":["rock"]},
    {"title":"First Day of My Life","artist":"Bright Eyes","videoId":"SJW9tg1zYXc","year":2005,"tags":["indie"]},
    {"title":"呢喃","artist":"Richie Jen","videoId":"nl4z-xV80R4","year":2000,"tags":["mandopop"]},
    {"title":"中國話","artist":"S.H.E","videoId":"tCKGoND0pS0","year":2003,"tags":["mandopop"]},
    {"title":"突然好想你","artist":"MAYDAY","videoId":"GtDRcXtDg-4","year":2008,"tags":["mandopop"]},
    {"title":"倔強 ","artist":"MAYDAY","videoId":"R2s-H_crYkc","year":2004,"tags":["mandopop"]},
    {"title":"浮躁","artist":"Eason Chan","videoId":"KgQx3Ob8l8A","year":2003,"tags":["cantopop"]},
    {"title":"十年","artist":"Eason Chan","videoId":"JM9rx_hN1Ko","year":2003,"tags":["mandopop"]},
    {"title":"K歌之王","artist":"Eason Chan","videoId":"9elvYViwP4g","year":2000,"tags":["cantopop"]},
    {"title":"Fix You","artist":"Coldplay","videoId":"k4V3Mo61fJM","year":2005,"tags":["rock"]},
    {"title":"The Scientist","artist":"Coldplay","videoId":"RB-RcX5DS5A","year":2002,"tags":["rock"]},
    {"title":"Clocks","artist":"Coldplay","videoId":"d020hcWA_Wg","year":2002,"tags":["rock"]},
    {"title":"Paradise","artist":"Coldplay","videoId":"1G4isv_Fylg","year":2011,"tags":["rock"]},
    {"title":"Adventure of a Lifetime","artist":"Coldplay","videoId":"QtXby3twMmI","year":2015,"tags":["rock"]},
    {"title":"You And Me","artist":"Lifehouse","videoId":"ac3HkriqdGQ","year":2005,"tags":["rock"]},
    {"title":"Smooth Criminal","artist":"Alien Ant Farm","videoId":"CDl9ZMfj6aE","year":2001,"tags":["rock"]},
    {"title":"Nobody","artist":"Wonder Girls","videoId":"QZBn1e9pr2Q","year":2008,"tags":["kpop"]},
    {"title":"Genie","artist":"Girls' Generation","videoId":"6SwiSpudKWI","year":2009,"tags":["kpop"]}
    {"title":"By the Way","artist":"Red Hot Chili Peppers","videoId":"PO5-rl43Rho","year":2002,"tags":["funk"]},
    {"title":"Yellow","artist":"Coldplay","videoId":"yKNxeF4KMsY","year":2000,"tags":["britpop"]},
    {"title":"光年之外","artist":"GEM","videoId":"T4SimnaiktU","year":2016,"tags":["mandopop"]},
    {"title":"夢到內河","artist":"Leslie Cheung","videoId":"MCxeySUIYFU","year":2001,"tags":["cantopop"]},
    {"title":"在回憶中","artist":"Sam Hui","videoId":"ZCdPWaT7RDU","year":2001,"tags":["cantopop"]}
  ],
  "10s": [
    {"title":"Rolling in the Deep","artist":"Adele","videoId":"rYEDA3JcQqw","year":2010,"tags":["pop"]},
    {"title":"Uptown Funk","artist":"Mark Ronson ft. Bruno Mars","videoId":"OPf0YbXqDm0","year":2014,"tags":["funk"]},
    {"title":"Shape of You","artist":"Ed Sheeran","videoId":"JGwWNGJdvx8","year":2017,"tags":["pop"]},
    {"title":"Bad Guy","artist":"Billie Eilish","videoId":"DyDfgMOUjCI","year":2019,"tags":["pop"]},
    {"title":"Gangnam Style","artist":"PSY","videoId":"9bZkp7q19f0","year":2012,"tags":["kpop"]},
    {"title":"Sorry","artist":"Justin Bieber","videoId":"fRh_vgS2dFE","year":2015,"tags":["pop"]},
    {"title":"Hello","artist":"Adele","videoId":"YQHsXMglC9A","year":2015,"tags":["pop"]},
    {"title":"Roar","artist":"Katy Perry","videoId":"CevxZvSJLk8","year":2013,"tags":["pop"]},
    {"title":"Blank Space","artist":"Taylor Swift","videoId":"e-ORhEE9VVg","year":2014,"tags":["pop"]},
    {"title":"Lean On","artist":"Major Lazer","videoId":"YqeW9_5kURI","year":2015,"tags":["edm"]},
    {"title":"Despacito","artist":"Luis Fonsi","videoId":"kJQP7kiw5Fk","year":2017,"tags":["latin"]},
    {"title":"Counting Stars","artist":"OneRepublic","videoId":"hT_nvWreIhg","year":2013,"tags":["pop"]},
    {"title":"Closer","artist":"The Chainsmokers","videoId":"PT2_F-1esPk","year":2016,"tags":["edm"]},
    {"title":"This Is America","artist":"Childish Gambino","videoId":"VYOjWnS4cMY","year":2018,"tags":["hiphop"]},
    {"title":"DNA","artist":"BTS","videoId":"MBdVXkSdhwU","year":2017,"tags":["kpop"]},
    {"title":"Faded","artist":"Alan Walker","videoId":"60ItHLz5WEA","year":2015,"tags":["edm"]},
    {"title":"Let Her Go","artist":"Passenger","videoId":"RBumgq5yVrA","year":2012,"tags":["pop"]},
    {"title":"Take Me to Church","artist":"Hozier","videoId":"PVjiKRfKpPI","year":2013,"tags":["indie"]},
    {"title":"Havana","artist":"Camila Cabello","videoId":"HCjNJDNzw8Y","year":2017,"tags":["pop"]},
    {"title":"Wake Me Up","artist":"Avicii","videoId":"IcrbM1l_BoI","year":2013,"tags":["edm"]}
  ],
  "20s": [
    {"title":"Blinding Lights","artist":"The Weeknd","videoId":"4NRXx6U8ABQ","year":2020,"tags":["pop"]},
    {"title":"As It Was","artist":"Harry Styles","videoId":"H5v3kku4y6Q","year":2022,"tags":["pop"]},
    {"title":"Flowers","artist":"Miley Cyrus","videoId":"G7KNmW9a75Y","year":2023,"tags":["pop"]},
    {"title":"Anti-Hero","artist":"Taylor Swift","videoId":"b1kbLwvqugk","year":2022,"tags":["pop"]},
    {"title":"Espresso","artist":"Sabrina Carpenter","videoId":"eVli-tstM5E","year":2024,"tags":["pop"]},
    {"title":"Stay","artist":"The Kid LAROI & Justin Bieber","videoId":"kTJczUoc26U","year":2021,"tags":["pop"]},
    {"title":"Levitating","artist":"Dua Lipa","videoId":"TUVcZfQe-Kw","year":2020,"tags":["pop"]},
    {"title":"Peaches","artist":"Justin Bieber","videoId":"tQ0yjYUFKAE","year":2021,"tags":["pop"]},
    {"title":"Watermelon Sugar","artist":"Harry Styles","videoId":"E07s5ZYygMg","year":2020,"tags":["pop"]},
    {"title":"Butter","artist":"BTS","videoId":"WMweEpGlu_U","year":2021,"tags":["kpop"]},
    {"title":"Pink Venom","artist":"BLACKPINK","videoId":"gQlMMD8auMs","year":2022,"tags":["kpop"]},
    {"title":"Unholy","artist":"Sam Smith","videoId":"Uq9gPaIzbe8","year":2022,"tags":["pop"]},
    {"title":"good 4 u","artist":"Olivia Rodrigo","videoId":"gNi_6U5Pm_o","year":2021,"tags":["pop"]},
    {"title":"Drivers License","artist":"Olivia Rodrigo","videoId":"ZmDBbnmKpqQ","year":2021,"tags":["pop"]},
    {"title":"Easy On Me","artist":"Adele","videoId":"U3ASj1L6_sY","year":2021,"tags":["pop"]},
    {"title":"Paint The Town Red","artist":"Doja Cat","videoId":"m4_9TFeMfJE","year":2023,"tags":["hiphop"]},
    {"title":"Calm Down","artist":"Rema","videoId":"WcIcVapfqXw","year":2022,"tags":["afrobeats"]},
    {"title":"Seven","artist":"Jungkook","videoId":"QU9c0053UAU","year":2023,"tags":["kpop"]},
    {"title":"Super Shy","artist":"NewJeans","videoId":"ArmDp-zijuc","year":2023,"tags":["kpop"]},
    {"title":"Houdini","artist":"Dua Lipa","videoId":"suAR1PYFNYA","year":2023,"tags":["pop"]}
  ]
}

const FAILED_KEY = 'retrotv-failed-videos'

export function getFailedVideos(): string[] {
  if (typeof window === 'undefined') return []
  try { return JSON.parse(localStorage.getItem(FAILED_KEY) || '[]') } catch { return [] }
}

export function markVideoAsFailed(videoId: string): void {
  if (typeof window === 'undefined') return
  try {
    const list = getFailedVideos()
    if (!list.includes(videoId))
      localStorage.setItem(FAILED_KEY, JSON.stringify([...list, videoId]))
  } catch {}
}

export function getRandomVideo(decade: Decade, history: string[], failed: string[] = []): VideoEntry | null {
  const list = videos[decade]
  const available = list.filter((v) => !failed.includes(v.videoId))
  if (available.length === 0) return null
  const filtered = available.filter((v) => !history.includes(v.videoId))
  const pool = filtered.length ? filtered : available
  return pool[Math.floor(Math.random() * pool.length)]
}
